package tr.yurdunubil.app

/**
 * Current-data questions refreshed from official Turkish sources.
 * The questions remain normal Question objects so every game mode can use them.
 * Source references are kept in explanations for learner-facing transparency.
 */
object CurrentQuestionBank {
    val all: List<Question> = listOf(
        Question(6001, topic = "Nüfus ve Yerleşme", text = "TÜİK'in 2025 ADNKS sonuçlarına göre Türkiye'nin 31 Aralık 2025 itibarıyla toplam nüfusu yaklaşık kaç kişidir?", options = listOf("76,1 milyon", "81,7 milyon", "86,1 milyon", "91,4 milyon", "96,8 milyon"), correctIndex = 2, explanation = "Doğru cevap 86,1 milyondur. TÜİK'e göre Türkiye nüfusu 86.092.168 kişidir. Kaynak: TÜİK, ADNKS 2025 (09.02.2026)."),
        Question(6002, topic = "Nüfus ve Yerleşme", text = "2025 ADNKS sonuçlarına göre Türkiye'nin yıllık nüfus artış hızı kaçtır?", options = listOf("Binde 1,2", "Binde 3,4", "Binde 5,0", "Binde 8,7", "Binde 12,1"), correctIndex = 2, explanation = "2024'te binde 3,4 olan yıllık nüfus artış hızı 2025'te binde 5'e yükselmiştir. Kaynak: TÜİK, ADNKS 2025."),
        Question(6003, topic = "Nüfus ve Yerleşme", text = "2025 ADNKS sonuçlarına göre Türkiye nüfusunun cinsiyet dağılımına ilişkin aşağıdakilerden hangisi doğrudur?", options = listOf("Kadın nüfus erkeklerden yaklaşık iki kat fazladır", "Erkek ve kadın nüfus oranları birbirine çok yakındır", "Erkek nüfus toplamın üçte ikisidir", "Kadın nüfus toplamın dörtte üçüdür", "Cinsiyet dağılımı yayımlanmamıştır"), correctIndex = 1, explanation = "Erkek nüfus %50,02, kadın nüfus %49,98'dir; dağılım neredeyse eşittir. Kaynak: TÜİK, ADNKS 2025."),
        Question(6004, topic = "Nüfus ve Yerleşme", text = "TÜİK'in 2025 ADNKS sonuçlarına göre Türkiye'de ikamet eden yabancı nüfus yaklaşık kaç kişidir?", options = listOf("519 bin", "1,52 milyon", "2,75 milyon", "4,10 milyon", "6,30 milyon"), correctIndex = 1, explanation = "2025 sonunda ikamet eden yabancı nüfus 1.519.515 kişidir. Kaynak: TÜİK, ADNKS 2025."),
        Question(6005, topic = "Nüfus ve Yerleşme", text = "2025 yılında Türkiye nüfusunun yaklaşık yüzde kaçı 0-17 yaş grubundaki çocuklardan oluşmuştur?", options = listOf("%14,8", "%18,2", "%21,0", "%24,8", "%31,5"), correctIndex = 3, explanation = "TÜİK'e göre 2025'te çocuk nüfusun toplam nüfus içindeki oranı %24,8'dir. Kaynak: TÜİK, İstatistiklerle Çocuk 2025."),
        Question(6006, topic = "Nüfus ve Yerleşme", text = "TÜİK'in 2025 yılı tanımına göre 15-24 yaş grubundaki genç nüfusun Türkiye toplam nüfusuna oranı yaklaşık kaçtır?", options = listOf("%9,6", "%12,1", "%14,8", "%18,7", "%24,8"), correctIndex = 2, explanation = "15-24 yaş grubu genç nüfus 12.708.348 kişi olup toplam nüfusun %14,8'ini oluşturmuştur. Kaynak: TÜİK, İstatistiklerle Gençlik 2025."),
        Question(6007, topic = "Maden ve Enerji", text = "Enerji ve Tabii Kaynaklar Bakanlığına göre 2026 Temmuz sonu itibarıyla Türkiye'nin elektrik kurulu gücü yaklaşık kaç MW'a ulaşmıştır?", options = listOf("96.476", "106.476", "116.476", "126.476", "136.476"), correctIndex = 3, explanation = "2026 Temmuz sonu itibarıyla kurulu güç 126.476 MW'tır. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı, Elektrik, güncelleme 19.08.2026."),
        Question(6008, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla Türkiye elektrik kurulu gücünde aşağıdaki kaynaklardan hangisinin payı en yüksektir?", options = listOf("Güneş", "Hidroelektrik", "Rüzgâr", "Doğal gaz", "Jeotermal"), correctIndex = 1, explanation = "Kurulu güçte hidroelektriğin payı %25,6 ile verilen seçenekler içinde en yüksektir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6009, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla Türkiye'nin elektrik kurulu gücünde güneş enerjisinin payı yaklaşık kaçtır?", options = listOf("%8,4", "%12,1", "%17,4", "%21,7", "%25,6"), correctIndex = 3, explanation = "Güneş enerjisinin kurulu güç içindeki payı %21,7'dir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı, 2026 Temmuz verileri."),
        Question(6010, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla güneş ve rüzgârın Türkiye elektrik kurulu gücündeki toplam payı yaklaşık kaçtır?", options = listOf("%21,7", "%25,6", "%31,4", "%33,8", "%42,5"), correctIndex = 3, explanation = "Güneş %21,7 ve rüzgâr %12,1 olmak üzere toplam %33,8'dir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6011, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla Türkiye'de lisanssız santraller de dâhil olmak üzere yaklaşık kaç elektrik üretim santrali bulunmaktadır?", options = listOf("13.553", "23.553", "33.553", "43.553", "53.553"), correctIndex = 3, explanation = "Santral sayısı 43.553'e ulaşmıştır. Bunun 41.458'i güneş santralidir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6012, topic = "Maden ve Enerji", text = "2025 yılında Türkiye'nin elektrik üretiminde verilen kaynaklardan hangisinin payı en yüksek olmuştur?", options = listOf("Güneş", "Rüzgâr", "Hidrolik", "Kömür", "Jeotermal"), correctIndex = 3, explanation = "2025 elektrik üretiminin %33,6'sı kömürden, %23'ü doğal gazdan gelmiştir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6013, topic = "Maden ve Enerji", text = "2025 yılında Türkiye'nin elektrik üretimi yaklaşık kaç TWh olarak gerçekleşmiştir?", options = listOf("262,9", "312,9", "342,9", "362,9", "402,9"), correctIndex = 3, explanation = "2025 yılında elektrik üretimi 362,9 TWh olmuştur. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6014, topic = "Tarım", text = "TÜİK'in 2025 bitkisel üretim sonuçlarına göre aşağıdaki ürünlerden hangisinin üretimi bir önceki yıla göre %38,5 azalmıştır?", options = listOf("Fındık", "Muz", "Mandalina", "Karpuz", "Kuru soğan"), correctIndex = 0, explanation = "2025'te fındık üretiminde %38,5 azalış gerçekleşmiştir. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6015, topic = "Tarım", text = "2025 yılında zeytin üretiminde bir önceki yıla göre yaklaşık ne kadar azalış gerçekleşmiştir?", options = listOf("%4,7", "%14,7", "%24,7", "%34,7", "%44,7"), correctIndex = 3, explanation = "TÜİK verisine göre zeytin üretimi 2025'te %34,7 azalmıştır. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6016, topic = "Tarım", text = "2025 yılında aşağıdaki narenciye ürünlerinden hangisinin üretimi artmıştır?", options = listOf("Portakal", "Limon", "Mandalina", "Hepsi", "Hiçbiri"), correctIndex = 2, explanation = "2025'te mandalina üretimi %5,8 artarken portakal ve limon üretimleri azalmıştır. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6017, topic = "Tarım", text = "2025 yılında meyveler, içecek ve baharat bitkileri üretim miktarı bir önceki yıla göre yaklaşık hangi yönde değişmiştir?", options = listOf("%30,9 artmıştır", "%10,0 artmıştır", "Değişmemiştir", "%10,0 azalmıştır", "%30,9 azalmıştır"), correctIndex = 4, explanation = "Bu gruptaki üretim miktarı yaklaşık %30,9 azalarak 19,6 milyon tona gerilemiştir. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6018, topic = "Tarım", text = "2025 yılında sert kabuklu meyveler arasında üretim azalışının en yüksek olduğu ürün hangisidir?", options = listOf("Fındık", "Ceviz", "Antep fıstığı", "Badem", "Kestane"), correctIndex = 2, explanation = "Antep fıstığında üretim azalışı %61,5 ile fındık (%38,5) ve cevizin (%38,2) üzerinde gerçekleşmiştir. Kaynak: TÜİK."),
        Question(6019, topic = "Tarım", text = "2025 yılında sebze ürünleri üretim miktarı yaklaşık kaç milyon ton olmuştur?", options = listOf("13,3", "23,3", "33,3", "43,3", "53,3"), correctIndex = 2, explanation = "Sebze ürünleri üretimi yaklaşık 33,3 milyon ton olmuş ve bir önceki yıla göre %0,9 azalmıştır. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6020, topic = "Tarım", text = "2025 yılında aşağıdaki sebzelerden hangisinin üretimi artmıştır?", options = listOf("Domates", "Salçalık kapya biber", "Hıyar", "Kuru soğan", "Hiçbiri"), correctIndex = 3, explanation = "Kuru soğan üretimi %9,8 artmıştır. Domates, kapya biber ve hıyar üretimleri ise azalmıştır. Kaynak: TÜİK."),
        Question(6021, topic = "Turizm", text = "2025 yılı verilerindeki tarımsal üretim düşüşleri coğrafya açısından yorumlandığında aşağıdakilerden hangisi en uygun çıkarımdır?", options = listOf("İklim ve üretim koşullarındaki yıllık değişimler tarımsal üretimi etkileyebilir", "Türkiye'de tarım tamamen sona ermiştir", "Tüm ürünler aynı oranda azalmıştır", "Tarımın iklimle ilişkisi yoktur", "Üretim değişimleri yalnızca nüfustan kaynaklanır"), correctIndex = 0, explanation = "Ürün bazında farklı oranlarda değişim görülmesi, iklimsel ve üretim koşullarının ürünlere göre farklı etkiler yaratabildiğini gösterir. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6022, topic = "Nüfus ve Yerleşme", text = "2025'te çocuk nüfus oranının %24,8 olması, önceki dönemlere göre uzun vadeli demografik dönüşüm açısından neyi düşündürür?", options = listOf("Çocuk nüfus oranının geçmişteki yüksek düzeylere göre gerilediğini", "Çocuk nüfusun toplam nüfusun tamamını oluşturduğunu", "Genç nüfusun sıfırlandığını", "Yaşlı nüfusun bulunmadığını", "Nüfusun her yıl aynı oranda arttığını"), correctIndex = 0, explanation = "TÜİK serisinde çocuk nüfus oranı 1970'te %48,5 iken 2025'te %24,8'e gerilemiştir; bu demografik yapının yaşlandığını düşündüren bir göstergedir. Kaynak: TÜİK, İstatistiklerle Çocuk 2025."),
        Question(6023, topic = "Nüfus ve Yerleşme", text = "2025 yılında 15-24 yaş grubunun toplam nüfus içindeki payının %14,8 olması aşağıdakilerden hangisiyle doğrudan ilişkilidir?", options = listOf("Genç nüfusun toplam nüfus içindeki ağırlığını ölçmesiyle", "Yalnızca kırsal nüfusu göstermesiyle", "Sadece yabancı nüfusu göstermesiyle", "Yüzölçümünü ifade etmesiyle", "Nüfus yoğunluğunu tek başına belirlemesiyle"), correctIndex = 0, explanation = "Bu oran genç nüfusun toplam nüfus içindeki payını ifade eder; nüfus yoğunluğu gibi alanla ilişkili bir ölçü değildir. Kaynak: TÜİK, İstatistiklerle Gençlik 2025."),
        Question(6024, topic = "Maden ve Enerji", text = "2026 Temmuz sonu verilerine göre güneş santrallerinin sayısının çok yüksek olması ile güneş enerjisinin kurulu güçteki payının %21,7 olması birlikte düşünüldüğünde hangi yorum daha uygundur?", options = listOf("Güneş enerjisinin hem yaygın tesis sayısına hem de önemli kurulu güce sahip olduğu", "Güneş enerjisinin Türkiye'de hiç kullanılmadığı", "Güneş santrallerinin tamamının hidroelektrik olduğu", "Kurulu güç ile santral sayısının aynı kavram olduğu", "Güneş enerjisinin yalnızca tek bir bölgede bulunduğu"), correctIndex = 0, explanation = "41.458 güneş santrali ve %21,7 kurulu güç payı, güneş enerjisinin sistemdeki ağırlığını gösterir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6025, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla yenilenebilir kaynakların Türkiye elektrik kurulu gücündeki toplam payı yaklaşık kaçtır?", options = listOf("%32,8", "%42,8", "%52,8", "%62,8", "%72,8"), correctIndex = 3, explanation = "Yenilenebilir kaynakların toplam kurulu güç içindeki payı %62,8'dir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6026, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla yerli kaynakların Türkiye elektrik kurulu gücündeki payı yaklaşık kaçtır?", options = listOf("%51,9", "%61,9", "%71,9", "%81,9", "%91,9"), correctIndex = 2, explanation = "Yerli kaynakların payı %71,9 olarak açıklanmıştır. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6027, topic = "Maden ve Enerji", text = "2026 Temmuz sonu verilerine göre hidroelektrik kurulu gücü yaklaşık kaç MW'tır?", options = listOf("22.344", "27.344", "32.344", "37.344", "42.344"), correctIndex = 2, explanation = "Hidroelektrik kurulu gücü 32.344 MW'tır. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6028, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla rüzgâr enerjisinin kurulu güçteki payı kaçtır?", options = listOf("%7,1", "%9,1", "%12,1", "%15,1", "%18,1"), correctIndex = 2, explanation = "Rüzgârın kurulu güçteki payı %12,1'dir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6029, topic = "Maden ve Enerji", text = "2025 yılında Türkiye'nin elektrik tüketimi bir önceki yıla göre yaklaşık yüzde kaç artmıştır?", options = listOf("%0,5", "%1,2", "%2,1", "%3,8", "%5,4"), correctIndex = 2, explanation = "2025 elektrik tüketimi %2,1 artarak 360,9 TWh olmuştur. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6030, topic = "Maden ve Enerji", text = "2025 yılında Türkiye'nin elektrik üretiminde doğal gazın payı yaklaşık kaçtır?", options = listOf("%13", "%18", "%23", "%28", "%33"), correctIndex = 2, explanation = "2025 elektrik üretiminin %23'ü doğal gazdan elde edilmiştir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6031, topic = "Maden ve Enerji", text = "2025 yılında Türkiye'nin elektrik üretiminde güneş enerjisinin payı yaklaşık kaçtır?", options = listOf("%5,5", "%8,5", "%10,5", "%12,5", "%15,5"), correctIndex = 2, explanation = "2025 elektrik üretiminin %10,5'i güneş enerjisinden elde edilmiştir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6032, topic = "Maden ve Enerji", text = "2025 yılında Türkiye'nin elektrik üretiminde rüzgâr enerjisinin payı yaklaşık kaçtır?", options = listOf("%5,9", "%8,9", "%10,9", "%12,9", "%15,9"), correctIndex = 2, explanation = "2025 elektrik üretiminde rüzgârın payı %10,9'dur. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6033, topic = "Tarım", text = "2025'te fındık, ceviz ve Antep fıstığı üretimlerindeki azalış oranları karşılaştırıldığında hangisi doğrudur?", options = listOf("Fındık azalışı en yüksektir", "Ceviz azalışı fındıktan daha yüksektir", "Antep fıstığı azalışı üçünün en yükseğidir", "Üçü de aynı oranda azalmıştır", "Üçünde de artış olmuştur"), correctIndex = 2, explanation = "Azalışlar sırasıyla fındık %38,5, ceviz %38,2 ve Antep fıstığı %61,5'tir; en yüksek azalış Antep fıstığındadır. Kaynak: TÜİK."),
        Question(6034, topic = "Tarım", text = "2025'te mandalina üretiminin artarken portakal ve limon üretiminin azalması aşağıdakilerden hangisini gösterir?", options = listOf("Aynı ürün grubundaki ürünlerin yıllık değişimlerinin bile farklılaşabileceğini", "Narenciyenin tamamının aynı oranda arttığını", "Narenciyenin tamamının aynı oranda azaldığını", "Tarımın iklimden bağımsız olduğunu", "Üretim verilerinin ürün bazında tutulmadığını"), correctIndex = 0, explanation = "Aynı ürün grubunda yer alan ürünlerin üretim değişimleri birbirinden farklı olabilir; 2025 verileri bunu açıkça göstermektedir. Kaynak: TÜİK."),
        Question(6035, topic = "Nüfus ve Yerleşme", text = "2025'te Türkiye nüfusunun 86.092.168 kişiye ulaşması, 2024'e göre nüfusun mutlak olarak arttığını mı göstermektedir?", options = listOf("Evet; nüfus 427.224 kişi artmıştır", "Hayır; nüfus 427.224 kişi azalmıştır", "Hayır; nüfus değişmemiştir", "Yalnızca yabancı nüfus artmıştır", "Yalnızca çocuk nüfus artmıştır"), correctIndex = 0, explanation = "TÜİK'e göre Türkiye nüfusu bir önceki yıla göre 427.224 kişi artmıştır. Kaynak: TÜİK, ADNKS 2025."),
        Question(6036, topic = "Nüfus ve Yerleşme", text = "2025 ADNKS'de erkek nüfusun %50,02, kadın nüfusun %49,98 olması aşağıdakilerden hangisine örnektir?", options = listOf("Cinsiyet oranlarının birbirine çok yakın olmasına", "Kırsal nüfusun kent nüfusundan fazla olmasına", "Nüfus yoğunluğunun sıfır olmasına", "Göçün sona ermesine", "Yaşlı nüfusun toplamın yarısı olmasına"), correctIndex = 0, explanation = "İki oran arasındaki fark yalnızca 0,04 puandır; cinsiyet dağılımı dengelidir. Kaynak: TÜİK, ADNKS 2025."),
        Question(6037, topic = "Tarım", text = "2025'te meyve üretimindeki %30,9'luk azalış ile sebze üretimindeki %0,9'luk azalış karşılaştırıldığında hangisi doğrudur?", options = listOf("Meyve grubundaki azalış daha belirgindir", "Sebze grubundaki azalış daha büyüktür", "İkisi eşittir", "Meyve üretimi artmıştır", "Sebze üretimi yarı yarıya azalmıştır"), correctIndex = 0, explanation = "%30,9'luk azalış %0,9'luk azalıştan çok daha büyüktür. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6038, topic = "Maden ve Enerji", text = "2026 Temmuz sonu kurulu güç verilerinde güneş ve rüzgârın toplam %33,8'lik paya ulaşması hangi eğilime işaret eder?", options = listOf("Değişken yenilenebilir kaynakların elektrik sistemindeki ağırlığının arttığına", "Kömürün tamamen ortadan kalktığına", "Hidroelektriğin kullanılmadığına", "Elektrik üretiminin sadece güneşten sağlandığına", "Doğal gaz santrallerinin tamamının kapandığına"), correctIndex = 0, explanation = "Güneş ve rüzgârın birlikte %33,8 kurulu güç payına ulaşması yenilenebilir kapasitenin önemli ağırlığını gösterir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6039, topic = "Nüfus ve Yerleşme", text = "TÜİK'in 2025 verilerine göre genç nüfus 12.708.348 kişi olduğuna göre aşağıdaki yorumlardan hangisi doğrudur?", options = listOf("Genç nüfus toplam nüfusun yaklaşık yedide birini oluşturur", "Genç nüfus toplam nüfusun yarısından fazladır", "Genç nüfus toplam nüfusun üçte ikisidir", "Genç nüfusun oranı %50'dir", "Genç nüfus tanımı 0-5 yaş grubudur"), correctIndex = 0, explanation = "%14,8 yaklaşık olarak yedide bire karşılık gelir. TÜİK genç nüfusu BM tanımıyla 15-24 yaş grubu olarak ele almaktadır."),
        Question(6040, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla 41.458 güneş santralinin bulunması, toplam 43.553 santral içinde hangi özelliği gösterir?", options = listOf("Santrallerin çok büyük bölümünün güneş kaynaklı olduğunu", "Santrallerin çoğunun hidroelektrik olduğunu", "Güneş santrallerinin yalnızca küçük bir bölüm olduğunu", "Santral sayısının 10 binden az olduğunu", "Rüzgâr santrallerinin tamamını"), correctIndex = 0, explanation = "41.458 güneş santrali, 43.553 toplam santral içinde açık ara çoğunluktadır. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6041, topic = "Tarım", text = "2025'te muz üretiminin %1,2 azalması ile zeytin üretiminin %34,7 azalması karşılaştırıldığında hangi sonuç çıkar?", options = listOf("Zeytin üretimindeki yıllık değişim çok daha büyüktür", "Muz üretimindeki değişim daha büyüktür", "İkisi eşittir", "Her iki ürün de artmıştır", "Veriler karşılaştırılamaz"), correctIndex = 0, explanation = "%34,7'lik azalış, %1,2'lik azalıştan çok daha büyüktür. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6042, topic = "Nüfus ve Yerleşme", text = "2025 yılında Türkiye'de yabancı nüfusun 1.519.515 kişi olması, toplam nüfusa göre yaklaşık nasıl bir büyüklüktür?", options = listOf("%1-2 aralığında", "%5-6 aralığında", "%10-11 aralığında", "%20-21 aralığında", "%30'un üzerinde"), correctIndex = 0, explanation = "1,52 milyonluk yabancı nüfus, 86,09 milyonluk toplam nüfusun yaklaşık %1,8'idir. Kaynak: TÜİK, ADNKS 2025."),
        Question(6043, topic = "Maden ve Enerji", text = "2025'te elektrik üretiminin 362,9 TWh, tüketimin ise 360,9 TWh olması aşağıdakilerden hangisini gösterir?", options = listOf("Üretimin tüketimden biraz daha yüksek gerçekleştiğini", "Tüketimin üretimin iki katı olduğunu", "Üretimin sıfır olduğunu", "Tüketimin 100 TWh'den az olduğunu", "Üretim ve tüketimin aynı olduğunu"), correctIndex = 0, explanation = "362,9 TWh üretim, 360,9 TWh tüketimden yaklaşık 2 TWh daha yüksektir. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6044, topic = "Tarım", text = "2025'te süs bitkileri üretiminin bir önceki yıla göre değişimi aşağıdakilerden hangisidir?", options = listOf("%1,4 artış", "%1,4 azalış", "%5,8 artış", "%8,7 azalış", "%10,4 artış"), correctIndex = 1, explanation = "Süs bitkileri üretimi 2025'te %1,4 azalmıştır. Kesme çiçek üretiminde %5,8 azalış, diğer süs bitkilerinde %8,7 artış görülmüştür. Kaynak: TÜİK."),
        Question(6045, topic = "Tarım", text = "2025 yılında süs bitkileri üretimi içinde kesme çiçeklerin payı yaklaşık kaçtır?", options = listOf("%16,4", "%33,6", "%50,0", "%66,4", "%83,6"), correctIndex = 3, explanation = "Kesme çiçekler süs bitkileri üretiminin %66,4'ünü, diğer süs bitkileri %33,6'sını oluşturmuştur. Kaynak: TÜİK."),
        Question(6046, topic = "Nüfus ve Yerleşme", text = "2025 yılında çocuk nüfusun %51,3'ünün erkek, %48,7'sinin kız olması hangi yorumu destekler?", options = listOf("Çocuk nüfusta erkeklerin payı az farkla daha yüksektir", "Kız çocukların payı iki kat fazladır", "Cinsiyet dağılımı yalnızca kentlerde ölçülmüştür", "Erkek çocukların payı %80'dir", "Cinsiyet verisi bulunmamaktadır"), correctIndex = 0, explanation = "Erkek çocukların payı %51,3 ile kız çocukların %48,7'sinden 2,6 puan daha yüksektir. Kaynak: TÜİK, İstatistiklerle Çocuk 2025."),
        Question(6047, topic = "Maden ve Enerji", text = "2026 Temmuz sonu verilerine göre doğal gazın kurulu güç içindeki payı %19,6 iken güneşin payı %21,7'dir. Buna göre hangisi doğrudur?", options = listOf("Güneşin kurulu güç payı doğal gazdan 2,1 puan daha yüksektir", "Doğal gaz güneşten 10 puan daha yüksektir", "İkisi eşittir", "Güneşin payı %10'dur", "Doğal gazın payı %5'tir"), correctIndex = 0, explanation = "21,7 - 19,6 = 2,1 puan. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6048, topic = "Tarım", text = "2025'te Antep fıstığı üretiminin %61,5 azalması ile fındık üretiminin %38,5 azalması arasındaki fark kaç yüzde puandır?", options = listOf("13", "18", "23", "28", "33"), correctIndex = 2, explanation = "61,5 - 38,5 = 23 yüzde puan. Kaynak: TÜİK, Bitkisel Üretim İstatistikleri 2025."),
        Question(6049, topic = "Maden ve Enerji", text = "2026 Temmuz sonu itibarıyla yenilenebilir kurulu güç 79.433 MW ve toplam kurulu güç 126.476 MW olduğuna göre yenilenebilirin payı hangi seçenekte doğru verilmiştir?", options = listOf("%42,8", "%52,8", "%57,8", "%62,8", "%72,8"), correctIndex = 3, explanation = "79.433 / 126.476 yaklaşık %62,8 eder. Kaynak: Enerji ve Tabii Kaynaklar Bakanlığı."),
        Question(6050, topic = "Nüfus ve Yerleşme", text = "2025 yılında Türkiye nüfusunun 86.092.168 kişiye çıkması ve yıllık nüfus artış hızının binde 5 olması birlikte düşünüldüğünde hangi ifade doğrudur?", options = listOf("Nüfus mutlak olarak artmış, artış hızı da 2024'e göre yükselmiştir", "Nüfus azalmış, artış hızı yükselmiştir", "Nüfus değişmemiştir", "Yalnızca yabancı nüfus artmıştır", "Artış hızı binde 50'dir"), correctIndex = 0, explanation = "2025 nüfusu 427.224 kişi artmış ve yıllık artış hızı 2024'teki binde 3,4'ten binde 5'e yükselmiştir. Kaynak: TÜİK, ADNKS 2025.")
    )
}
