package tr.yurdunubil.app

/** Additional editor-style questions for the shared game, event and arena pool. */
object ExpansionQuestionBank {
    val all = listOf(
        Question(1001, topic = "Jeolojik Yapı", text = "Türkiye'nin genç oluşumlu ve hareketli bir jeolojik yapıya sahip olması aşağıdakilerden hangisinin yaygın görülmesinde daha doğrudan etkilidir?", options = listOf("Depremlerin", "Gelgitlerin", "Mercan resiflerinin", "Muson yağışlarının", "Buzul çağlarının"), correctIndex = 0, explanation = "Türkiye aktif tektonik kuşak üzerinde bulunduğu için deprem etkinliği yüksektir."),
        Question(1002, topic = "Yer Şekilleri", text = "Ege kıyılarında dağların denize dik uzanması aşağıdakilerden hangisine ortam hazırlayan faktörlerden biridir?", options = listOf("Koy ve körfezlerin kıyı boyunca içeri sokulmasına", "Kıyıların tamamen düzleşmesine", "Kıyı ile iç kesim arasında ulaşımın zorlaşmasına", "Kar yağışının her yerde artmasına", "Akarsuların denize ulaşamamasına"), correctIndex = 0, explanation = "Dağların kıyıya dik uzanması vadilerin denize açılmasını ve girintili-çıkıntılı kıyıların oluşmasını kolaylaştırır."),
        Question(1003, topic = "Kıyı Tipleri", text = "Türkiye'de ria tipi kıyıların oluşmasında aşağıdakilerden hangisi temel rol oynar?", options = listOf("Akarsu vadilerinin deniz altında kalması", "Dağların buzullarla aşınması", "Mercanların birikmesi", "Rüzgârın kum biriktirmesi", "Volkan konilerinin çökmesi"), correctIndex = 0, explanation = "Ria kıyılarında akarsu vadilerinin deniz seviyesinin yükselmesiyle sular altında kalması etkilidir."),
        Question(1004, topic = "Su Varlığı", text = "Fırat ve Dicle nehirlerinin Türkiye açısından ortak özelliklerinden biri aşağıdakilerden hangisidir?", options = listOf("Güneydoğu Anadolu'da sulama ve enerji açısından önem taşımaları", "Karadeniz'e dökülmeleri", "Tamamının Türkiye sınırları içinde doğup denize ulaşması", "Düzensiz rejimli olmamaları", "Marmara Bölgesi'nden geçmeleri"), correctIndex = 0, explanation = "Fırat ve Dicle Güneydoğu Anadolu'da sulama ve hidroelektrik potansiyel açısından önemlidir."),
        Question(1005, topic = "İklim ve Bitki Örtüsü", text = "Bir merkezde kış sıcaklıklarının kıyıdaki aynı enleme göre daha düşük olması aşağıdakilerden hangisiyle daha iyi açıklanır?", options = listOf("Karasallık ve yükselti", "Boylam farkı", "Deniz seviyesinin yükselmesi", "Gelgit", "Kıyı uzunluğu"), correctIndex = 0, explanation = "Denizden uzaklaşma ve yükseltinin artması kış sıcaklıklarının düşmesine katkıda bulunur."),
        Question(1006, topic = "İklim ve Bitki Örtüsü", text = "Karadeniz kıyılarında ormanların geniş alan kaplamasında aşağıdakilerden hangisi daha etkilidir?", options = listOf("Yıl boyunca nemli koşulların bulunması", "Yaz kuraklığının çok şiddetli olması", "Yükseltinin her yerde sıfır olması", "Çöl rüzgârlarının etkisi", "Yağışın yalnızca kışın görülmesi"), correctIndex = 0, explanation = "Yüksek ve yıl içine yayılan yağış, nemli koşulların oluşmasını ve gür ormanların gelişmesini destekler."),
        Question(1007, topic = "Toprak", text = "Çukurova gibi delta ovalarında tarımsal verimliliğin yüksek olmasında aşağıdakilerden hangisi daha doğrudan etkilidir?", options = listOf("Alüvyal toprakların bulunması", "Yüksek dağların yaygınlığı", "Kalıcı kar örtüsü", "Tundra bitkileri", "Buzul vadileri"), correctIndex = 0, explanation = "Akarsuların taşıdığı mineralce zengin alüvyonların birikmesi verimli tarım toprakları oluşturabilir."),
        Question(1008, topic = "Nüfus ve Yerleşme", text = "Aşağıdakilerden hangisi nüfusun bir merkezde toplanmasını sağlayan beşerî faktörlerden biridir?", options = listOf("Sanayi ve hizmet sektörlerinin gelişmişliği", "Yükseltinin fazla olması", "Eğimin artması", "Kuraklığın şiddetlenmesi", "Doğal bitki örtüsünün gürleşmesi"), correctIndex = 0, explanation = "İş ve hizmet olanakları nüfus için çekim oluşturur ve yoğunluğu artırabilir."),
        Question(1009, topic = "Nüfus ve Yerleşme", text = "Nüfus yoğunluğu ile nüfus miktarı arasındaki farkı gösteren en doğru ifade hangisidir?", options = listOf("Yoğunluk alan başına düşen nüfusu, miktar ise toplam nüfusu ifade eder.", "Yoğunluk yalnızca göçü, miktar yalnızca iklimi gösterir.", "İkisi aynı kavramdır.", "Yoğunluk yalnızca şehirlerde hesaplanır.", "Miktar yüz ölçümüne bölünmüş değerdir."), correctIndex = 0, explanation = "Nüfus yoğunluğu toplam nüfusun yüz ölçümüne oranıdır; nüfus miktarı ise toplam kişi sayısıdır."),
        Question(1010, topic = "Tarım", text = "Bir tarım ürününün belirli bir bölgede yetişebilmesi için aşağıdakilerden hangisi öncelikle değerlendirilmelidir?", options = listOf("Ürünün sıcaklık ve su isteği ile bölgenin iklim koşulları", "İlin plaka kodu", "Meridyen sayısı tek başına", "Nüfusun toplamı tek başına", "Liman sayısı tek başına"), correctIndex = 0, explanation = "Tarım ürünlerinin yetişme koşullarında sıcaklık, yağış ve sulama gibi iklimsel faktörler temel belirleyicilerdir."),
        Question(1011, topic = "Tarım", text = "Doğu Karadeniz'de çay tarımının gelişebilmesinde aşağıdakilerden hangisi diğerlerine göre daha belirleyicidir?", options = listOf("Nemli ve yağışlı iklim", "Yaz kuraklığının çok uzun sürmesi", "Geniş bozkır alanları", "Çöl toprakları", "Kalıcı don"), correctIndex = 0, explanation = "Çay, yüksek nem ve yağış isteyen bir bitkidir; bu nedenle Doğu Karadeniz koşulları elverişlidir."),
        Question(1012, topic = "Tarım", text = "Hayvancılığın geniş mera alanlarına bağlı olarak geliştiği bir yörede aşağıdakilerden hangisinin yapılması daha olasıdır?", options = listOf("Büyükbaş veya küçükbaş hayvancılığın yaygınlaşması", "Çay tarımının zorunlu olması", "Kıyı turizminin gelişmesi", "Liman ticaretinin artması", "Seracılığın tek faaliyet olması"), correctIndex = 0, explanation = "Mera varlığı özellikle otlatmaya dayalı hayvancılığın gelişmesini destekler."),
        Question(1013, topic = "Maden ve Enerji", text = "Bir madenin çıkarıldığı yerde işlenmesinin tercih edilmesinde aşağıdakilerden hangisi etkili olabilir?", options = listOf("Taşıma maliyetini azaltmak", "Yerel saati değiştirmek", "Enlemi artırmak", "Yağışı durdurmak", "Kıyı tipini değiştirmek"), correctIndex = 0, explanation = "Ağır veya taşınması maliyetli hammaddelerin kaynağa yakın işlenmesi taşıma maliyetini düşürebilir."),
        Question(1014, topic = "Maden ve Enerji", text = "Aşağıdaki eşleştirmelerden hangisi yanlıştır?", options = listOf("Kırka — Bor", "Zonguldak — Taş kömürü", "Batman — Petrol", "Divriği — Demir", "Rize — Taş kömürü"), correctIndex = 4, explanation = "Rize taş kömürüyle değil, başta çay tarımı olmak üzere farklı ekonomik faaliyetlerle öne çıkar."),
        Question(1015, topic = "Sanayi ve Ulaşım", text = "Sanayinin büyük pazarlara yakın kurulmasının temel avantajı aşağıdakilerden hangisidir?", options = listOf("Ürünlerin tüketiciye daha kolay ulaştırılması", "Yükseltinin azalması", "Yerel saat farkının yok olması", "Yağışın artması", "Fayların ortadan kalkması"), correctIndex = 0, explanation = "Büyük pazarlar ürünlerin satışını ve dağıtımını kolaylaştırarak sanayi için çekim oluşturur."),
        Question(1016, topic = "Sanayi ve Ulaşım", text = "Boğazların ulaşım açısından stratejik olmasının temel nedeni aşağıdakilerden hangisidir?", options = listOf("Denizleri birbirine bağlayan doğal geçiş alanları olmaları", "Türkiye'nin en yüksek dağlarını oluşturmaları", "Tüm akarsuların kaynağını oluşturmaları", "Tarım alanlarını artırmaları", "Karasal iklimi ortadan kaldırmaları"), correctIndex = 0, explanation = "İstanbul ve Çanakkale Boğazları denizler arasındaki doğal geçişleri sağladıkları için stratejiktir."),
        Question(1017, topic = "Turizm", text = "Kapadokya'daki peri bacalarının oluşumunda aşağıdakilerden hangisi birlikte rol oynamıştır?", options = listOf("Volkanik tüflerin oluşması ve aşınması", "Mercan resifleri ve gelgit", "Buzul birikimi ve tsunami", "Delta birikimi ve kıyı akıntısı", "Rüzgârla kumul oluşumu ve mercanlar"), correctIndex = 0, explanation = "Volkanik tüfler zamanla akarsu ve rüzgâr aşındırmasıyla şekillenmiştir."),
        Question(1018, topic = "Turizm", text = "Uludağ'ın turizm açısından öne çıkmasında aşağıdakilerden hangisi daha doğrudan etkilidir?", options = listOf("Yüksek ve karlı dağlık alan olması", "Delta ovasında bulunması", "Çöl iklimine sahip olması", "Petrol sahası olması", "Kıyı lagünü olması"), correctIndex = 0, explanation = "Uludağ'ın yükseltisi ve kar koşulları kış turizmini destekler."),
        Question(1019, topic = "Bölgeler", text = "Aşağıdakilerden hangisi Güneydoğu Anadolu Projesi'nin tarımsal etkilerinden biridir?", options = listOf("Sulama olanaklarının artması", "Çay tarımının kıyılara yayılması", "Karadeniz ormanlarının genişlemesi", "Marmara sanayisinin ortadan kalkması", "Tundra alanlarının artması"), correctIndex = 0, explanation = "GAP kapsamında sulama yatırımları özellikle tarımsal üretim desenini ve verimi etkiler."),
        Question(1020, topic = "Bölgeler", text = "Yüz ölçümü bakımından en büyük coğrafi bölgenin nüfus yoğunluğunun Marmara'dan düşük olmasının temel nedenlerinden biri hangisidir?", options = listOf("Yükselti ve engebeliliğin daha fazla olması", "Sanayinin tamamen yasak olması", "Denize kıyısının bulunmaması", "Yağışın hiç görülmemesi", "Tüm arazinin çöl olması"), correctIndex = 0, explanation = "Doğu Anadolu'nun yüksek ve engebeli yapısı yerleşme ve ekonomik faaliyetlerin dağılışını sınırlar."),
        Question(1021, topic = "Harita Bilgisi", text = "Aynı iki merkez arasındaki gerçek uzaklık değişmediği hâlde küçük ölçekli haritada bu uzaklık neden daha kısa görünür?", options = listOf("Harita daha geniş alanı daha az ayrıntıyla gösterdiği için", "Meridyenler kaybolduğu için", "Yükselti değiştiği için", "Gerçek uzaklık azaldığı için", "Kuzey yönü değiştiği için"), correctIndex = 0, explanation = "Küçük ölçekli haritalarda ayrıntı azalır ve daha geniş alan daha küçük gösterimle temsil edilir."),
        Question(1022, topic = "Harita Bilgisi", text = "İzohips haritasında kapalı eğrilerin değerleri merkeze doğru artıyorsa merkezde hangi özellik vardır?", options = listOf("Tepe", "Çukur", "Delta", "Vadi tabanı", "Kıyı ovası"), correctIndex = 0, explanation = "Kapalı izohipslerde yükselti merkeze doğru artıyorsa merkez bir tepeyi gösterir."),
        Question(1023, topic = "Doğal Afetler", text = "Karadeniz'de heyelan riskinin bazı yamaçlarda yüksek olmasının en uygun açıklaması hangisidir?", options = listOf("Eğimli arazi ile fazla yağışın birleşmesi", "Kuraklık ile düz arazinin birleşmesi", "Çöl ikliminin yaygın olması", "Gelgit genliğinin çok yüksek olması", "Tüm arazinin alüvyal olması"), correctIndex = 0, explanation = "Fazla yağış yamaçları suya doyurabilir; eğim de kütle hareketlerini kolaylaştırır."),
        Question(1024, topic = "Ekonomik Coğrafya", text = "Bir bölgede hem tarım hem sanayinin gelişmesi aşağıdakilerden hangisini güçlendirebilir?", options = listOf("Tarım ürünlerinin sanayi hammaddesi olarak değerlendirilmesini", "Yerel saat farkının ortadan kalkmasını", "Yükseltinin azalmasını", "Fayların kapanmasını", "İklimin değişmesini"), correctIndex = 0, explanation = "Tarım-sanayi bağlantısı, tarımsal ürünlerin işlenerek katma değerli ürünlere dönüşmesini sağlar."),
        Question(1025, topic = "Coğrafi Konum", text = "Türkiye'nin doğusu ile batısı arasında yerel saat farkının bulunması aşağıdakilerden hangisinin sonucudur?", options = listOf("Doğu-batı yönünde meridyen farkının bulunmasının", "Kuzey-güney yönünde paralel farkının bulunmasının", "Yükseltinin değişmesinin", "Denizlerin çevrelemesinin", "Dağların uzanışının"), correctIndex = 0, explanation = "Yerel saat farkı boylam farkından kaynaklanır; Türkiye doğu-batı yönünde farklı meridyenler üzerinde yer alır.")
    )
}
