package tr.yurdunubil.app

data class LearningNote(
    val title: String,
    val summary: String,
    val keyPoints: List<String>,
    val examTip: String
)

/** Exam-oriented, paraphrased learning notes. */
object GeographyLibraryContent {
    val notes = listOf(
        LearningNote("Coğrafi Konum", "Türkiye'nin matematik ve özel konumunu sonuçlarıyla birlikte öğren.", listOf("36–42° Kuzey enlemleri", "26–45° Doğu boylamları", "Asya–Avrupa geçiş alanı", "Boğazlar ve ulaşım koridorları"), "Önce verilen sonucun enlem mi boylam mı, yoksa özel konum mu olduğunu ayır."),
        LearningNote("Yer Şekilleri", "Dağ, ova, plato ve kıyı şekillerini bölgesel sonuçlarıyla bağla.", listOf("Kuzey Anadolu Dağları", "Toroslar", "Platolar", "Ege'de dağların kıyıya dik uzanması", "Karstik alanlar"), "Dağların uzanışını; ulaşım, iklim ve kıyı-iç kesim ilişkisiyle beraber düşün."),
        LearningNote("Su Varlığı", "Akarsuları, gölleri ve havzaları harita mantığıyla öğren.", listOf("Kızılırmak", "Yeşilırmak", "Fırat–Dicle", "Van Gölü", "Kapalı havzalar"), "Bir akarsuyu ezberlemek yerine kaynağı, izlediği yön ve döküldüğü yeri zihninde canlandır."),
        LearningNote("İklim ve Bitki Örtüsü", "İklim tiplerini sıcaklık, yağış ve bitki örtüsü üzerinden karşılaştır.", listOf("Akdeniz–maki", "Karadeniz–orman", "İç Anadolu–bozkır", "Yükselti arttıkça sıcaklığın azalması", "Denizelliğin sıcaklık farklarını azaltması"), "Bitkiyi doğrudan ezberleme; yağış ve sıcaklık koşulundan çıkar."),
        LearningNote("Nüfus ve Yerleşme", "Nüfus dağılışını doğal koşullar ve ekonomik çekim merkezleriyle birlikte değerlendir.", listOf("Marmara yoğunluğu", "Sanayi ve hizmetler", "Ulaşım merkezleri", "İç göç", "Kırsal–kentsel yerleşme"), "'Neden burada nüfus fazla?' sorusunda doğal koşullar + ekonomi + ulaşımı birlikte sorgula."),
        LearningNote("Tarım ve Hayvancılık", "Ürün ve hayvancılık türlerini iklim, sulama, toprak ve pazarla ilişkilendir.", listOf("Çay–Doğu Karadeniz", "Fındık–Karadeniz", "Zeytin–Ege/Akdeniz kıyıları", "Pamuk–sıcak ve sulanabilen alanlar", "Mera hayvancılığı–yüksek/otlak alanlar"), "Ürünü görünce önce yetişme koşulunu düşün, sonra bölgeyi seç."),
        LearningNote("Maden ve Enerji", "Madenleri çıkarım alanları ve kullanım özellikleriyle eşleştir.", listOf("Bor", "Taş kömürü–Zonguldak", "Petrol–Batman çevresi", "Linyit", "Hidroelektrik–akarsu ve eğim"), "Şehir + maden eşleşmelerini küçük kartlar halinde tekrar et; benzer madenleri karıştırma."),
        LearningNote("Sanayi ve Ulaşım", "Sanayinin dağılışını hammadde, pazar, sermaye, iş gücü ve ulaşım üzerinden yorumla.", listOf("Marmara sanayi yoğunluğu", "Limanların ticarete katkısı", "Boğazların stratejik önemi", "Karayolu–demiryolu bağlantısı", "Ulaşım koridorları"), "Tek bir faktöre bağlanma; sanayi sorularında birden fazla çekim unsurunu ara."),
        LearningNote("Turizm", "Doğal ve kültürel turizm merkezlerini harita üzerinde konumlandır.", listOf("Pamukkale–Denizli", "Kapadokya–Nevşehir çevresi", "Efes–İzmir", "Uludağ–Bursa", "Akdeniz kıyıları"), "Sorudaki doğal oluşum veya tarihî eser ipucunu önce bölgeye, sonra merkeze bağla."),
        LearningNote("Bölgeler", "Yedi bölgeyi ezber listesi yerine ayırt edici özelliklerle karşılaştır.", listOf("Marmara–sanayi ve yoğun nüfus", "Ege–girintili kıyılar ve tarım", "Akdeniz–kıyı turizmi", "Karadeniz–yağış ve orman", "İç Anadolu–bozkır/tahıl", "Doğu Anadolu–yükselti", "Güneydoğu–GAP"), "Bir bölge sorusunda önce en güçlü ayırt edici ipucunu bul."),
        LearningNote("Doğal Afetler", "Afetleri oluşum koşulları ve Türkiye'deki dağılışlarıyla ilişkilendir.", listOf("Deprem–aktif faylar", "Heyelan–eğim + yağış", "Sel–şiddetli yağış + drenaj", "Çığ–eğim + kar örtüsü", "Erozyon–bitki örtüsü ve yanlış arazi kullanımı"), "Olayı değil oluşum şartını sor: 'Bu koşullar nerede güçlü?' diye düşün."),
        LearningNote("Toprak ve Bitki", "Toprakları oluşum koşulları ve görüldükleri alanlarla ayırt et.", listOf("Kahverengi orman–Karadeniz", "Terra rossa–Akdeniz karstik alanları", "Çernezyom–Erzurum-Kars", "Halomorfik–tuzlu/kurak alanlar", "Alüvyal–akarsu birikimi"), "Toprak adını gördüğünde renk + iklim + kayaç/oluşum koşulunu birlikte hatırla."),
        LearningNote("Harita Bilgisi", "Ölçek, izohips ve profil sorularını görsel mantıkla çöz.", listOf("Büyük ölçek–fazla ayrıntı", "Küçük ölçek–geniş alan", "Sık izohips–fazla eğim", "İzohipslerden yükseltiyi okuma", "Profil çıkarma"), "Haritada sadece tek çizgiye değil; izohips aralığı, sıklığı ve yükselti değerlerine birlikte bak."),
        LearningNote("Su, Toprak ve Bitki Bağlantısı", "Doğal sistemleri ayrı ezberlemek yerine birbirine bağla.", listOf("İklim → bitki örtüsü", "Bitki → toprak oluşumu", "Eğim → erozyon/heyelan", "Akarsu → aşındırma/biriktirme", "Sulama → tarımsal üretim"), "ÖSYM tarzı yorumlarda cevabı tek başlıkta değil, iki veya üç coğrafi sürecin kesişiminde ara."),
        LearningNote("İklim Sorularının Anahtarı", "Sıcaklık, basınç, rüzgâr ve yağışı neden-sonuç zinciriyle çöz.", listOf("Enlem → sıcaklık", "Yükselti → sıcaklık azalması", "Denizellik → sıcaklık farklarının azalması", "Yükselici hava → yağış eğilimi", "Bakı → güneşlenme farkı"), "Soruda önce hava olayının nedenini bul; sonucu ezberlenmiş tek kelimeyle seçme."),
        LearningNote("Akarsu Sistematiği", "Aşındırma, taşıma ve biriktirme süreçlerini akış koşullarıyla eşleştir.", listOf("Eğim fazla → enerji artar", "Eğim az → yana aşındırma artabilir", "Ağız kesimi → birikme ihtimali", "Rejim → debinin yıl içindeki değişimi", "Havza → su toplama alanı"), "Akarsuyu gördüğünde önce eğim + debi + taşıdığı malzeme üçlüsünü düşün."),
        LearningNote("Ekonomik Coğrafyada Yer Seçimi", "Tarım, sanayi ve hizmetlerin neden belirli merkezlerde toplandığını çöz.", listOf("Hammadde", "Pazar", "Ulaşım", "İş gücü", "Sermaye ve enerji"), "'Neden burada?' sorusunun cevabı çoğunlukla tek değil, birkaç ekonomik faktörün bileşimidir."),
        LearningNote("Nüfus Sorularının Şifresi", "Nüfus miktarı, yoğunluğu, yapısı ve hareketlerini birbirinden ayır.", listOf("Nüfus miktarı ≠ yoğunluk", "Doğum–ölüm → doğal artış", "Alınan–verilen göç → net göç", "Yaş yapısı → iş gücü ve bağımlılık", "Ekonomi → çekici merkezler"), "Sorudaki kavramın 'kaç kişi', 'nerede yoğun', 'hangi yaşta' ya da 'hangi hareket' olduğunu önce belirle."),
        LearningNote("Türkiye'de Tarımın Mantığı", "Ürünleri yalnızca il adıyla değil yetişme koşullarıyla öğren.", listOf("Çay → nem", "Zeytin → ılıman kış", "Pamuk → sıcaklık + sulama", "Buğday → karasal koşullara uyum", "Şeker pancarı → ılıman koşullar + su"), "Ürünü görünce üç soru sor: hangi sıcaklık, ne kadar su, hangi toprak/alan?"),
        LearningNote("Risk ve Doğal Afet Yönetimi", "Afet sorularında sadece tehlikeyi değil, insan kaynaklı risk artırıcıları da değerlendir.", listOf("Deprem → zemin + yapı", "Sel → geçirimsiz yüzey + drenaj", "Heyelan → eğim + su", "Erozyon → yanlış arazi kullanımı", "Çığ → kar + eğim"), "'Afeti durdur' değil, 'riski azalt' mantığıyla önlemleri değerlendir.")
    )
}
