package tr.yurdunubil.app

/** Expanded local KPSS Türkiye Coğrafyası bankası. */
object GeographyQuestions {
    val all: List<Question> = SampleQuestions.all + listOf(
        Question(19, topic = "Maden ve Enerji", text = "Türkiye'de bor minerallerinin çıkarılmasıyla öne çıkan merkezlerden biri hangisidir?", options = listOf("Kırka", "Zonguldak", "Batman", "Divriği", "Elbistan"), correctIndex = 0, explanation = "Eskişehir Kırka, Türkiye'nin önemli bor yataklarının bulunduğu merkezlerden biridir."),
        Question(20, topic = "Maden ve Enerji", text = "Batman çevresinde çıkarılmasıyla öne çıkan enerji kaynağı hangisidir?", options = listOf("Petrol", "Taş kömürü", "Bor", "Doğal gaz", "Uranyum"), correctIndex = 0, explanation = "Batman ve çevresi Türkiye'nin önemli petrol üretim alanlarından biridir."),
        Question(21, topic = "Maden ve Enerji", text = "Türkiye'de hidroelektrik enerji potansiyelinin yüksek olmasında aşağıdakilerden hangisi daha etkilidir?", options = listOf("Yükselti ve eğimin fazla olması", "Kıyıların kısa olması", "Ormanların az olması", "Nüfusun seyrek olması", "Enlemin düşük olması"), correctIndex = 0, explanation = "Yükselti farkları ve eğimli arazi, akarsuların hidroelektrik potansiyelini artırır."),
        Question(22, topic = "Turizm", text = "Kapadokya'nın peri bacalarıyla öne çıkmasında hangi doğal süreçlerin birlikte etkisi vardır?", options = listOf("Volkanik birikim ve aşındırma", "Buzul aşındırması ve gelgit", "Mercan oluşumu ve dalga", "Rüzgar birikimi ve tsunami", "Karstik çökme ve heyelan"), correctIndex = 0, explanation = "Volkanik tüflerin oluşması ve sonrasında akarsu-rüzgar aşındırması peri bacalarının şekillenmesinde etkilidir."),
        Question(23, topic = "Turizm", text = "Türkiye'de kış turizmi merkezlerinden biri aşağıdakilerden hangisidir?", options = listOf("Uludağ", "Çukurova", "Bafra", "Harran", "Gediz"), correctIndex = 0, explanation = "Bursa'daki Uludağ önemli bir kış turizmi merkezidir."),
        Question(24, topic = "Turizm", text = "Efes Antik Kenti hangi ilimizde bulunur?", options = listOf("İzmir", "Antalya", "Denizli", "Çanakkale", "Mersin"), correctIndex = 0, explanation = "Efes Antik Kenti İzmir'in Selçuk ilçesi yakınlarındadır."),
        Question(25, topic = "Harita Bilgisi", text = "Ölçek küçüldükçe haritada gösterilen alan için aşağıdakilerden hangisi doğrudur?", options = listOf("Gösterilen alan büyür, ayrıntı azalır", "Gösterilen alan küçülür, ayrıntı artar", "Ayrıntı değişmez", "Yükselti ortadan kalkar", "Yönler değişir"), correctIndex = 0, explanation = "Küçük ölçekli haritalar daha geniş alanları gösterir ancak ayrıntı düzeyi daha düşüktür."),
        Question(26, topic = "Harita Bilgisi", text = "İzohipslerin birbirine çok yaklaştığı yerde eğim nasıldır?", options = listOf("Fazladır", "Azdır", "Sıfırdır", "Her zaman aynıdır", "Belirlenemez"), correctIndex = 0, explanation = "İzohipslerin sıklaşması kısa mesafede büyük yükselti değişimi olduğunu, yani eğimin fazla olduğunu gösterir."),
        Question(27, topic = "Harita Bilgisi", text = "Bir haritada kuzey yönünü bulmak için en temel yön göstergesi hangisidir?", options = listOf("Kuzey oku", "Lejant", "Ölçek çubuğu", "İzohips", "Koordinat tablosu"), correctIndex = 0, explanation = "Kuzey oku haritanın yönlendirilmesini sağlar."),
        Question(28, topic = "Doğal Afetler", text = "Türkiye'de deprem riskinin yüksek olmasının temel nedenlerinden biri nedir?", options = listOf("Aktif fay hatlarının bulunması", "Kıyıların uzunluğu", "Ormanların genişliği", "Akarsu sayısının azlığı", "Çöl ikliminin yaygınlığı"), correctIndex = 0, explanation = "Türkiye aktif tektonik kuşak üzerinde yer alır ve önemli fay sistemlerine sahiptir."),
        Question(29, topic = "Doğal Afetler", text = "Karadeniz'in özellikle eğimli yamaçlarında heyelan riskinin yüksek olmasında hangisi birlikte etkilidir?", options = listOf("Fazla yağış ve eğim", "Kuraklık ve düz arazi", "Düşük nem ve yüksek basınç", "Çölleşme ve tuzluluk", "Gelgit ve tsunami"), correctIndex = 0, explanation = "Yağışın fazla olması yamaçları suya doyurur; eğim de kütle hareketini kolaylaştırır."),
        Question(30, topic = "Nüfus ve Yerleşme", text = "Türkiye'de nüfus yoğunluğunun en yüksek olduğu bölge hangisidir?", options = listOf("Marmara", "Doğu Anadolu", "Karadeniz", "Güneydoğu Anadolu", "İç Anadolu"), correctIndex = 0, explanation = "Sanayi, ticaret, ulaşım ve hizmetlerin yoğunluğu Marmara'da nüfus yoğunluğunu artırır."),
        Question(31, topic = "Nüfus ve Yerleşme", text = "Türkiye'de iç göçlerin büyük kentlere yönelmesinde aşağıdakilerden hangisi temel nedenlerden biridir?", options = listOf("İş ve eğitim olanakları", "Yükseltinin her yerde aynı olması", "Yağışın tamamen ortadan kalkması", "Kıyıların uzaması", "Meridyen sayısının değişmesi"), correctIndex = 0, explanation = "İş, eğitim, sağlık ve hizmet olanakları büyük kentlere göçü destekleyen önemli çekim faktörleridir."),
        Question(32, topic = "Sanayi ve Ulaşım", text = "İstanbul ve çevresinin sanayi açısından gelişmesinde aşağıdakilerden hangisi daha doğrudan etkilidir?", options = listOf("Pazar, ulaşım ve sermaye olanakları", "Yüksek plato alanları", "Çok az nüfus", "Kurak iklim", "Tarım arazilerinin tamamen yokluğu"), correctIndex = 0, explanation = "Geniş pazar, gelişmiş ulaşım, sermaye ve iş gücü İstanbul çevresindeki sanayiyi destekler."),
        Question(33, topic = "Sanayi ve Ulaşım", text = "Türkiye'nin boğazlara sahip olması aşağıdaki ulaşım türlerinden hangisinin önemini artırır?", options = listOf("Deniz ulaşımı", "Hava ulaşımı", "Yalnızca karayolu", "Yalnızca demiryolu", "Teleferik ulaşımı"), correctIndex = 0, explanation = "İstanbul ve Çanakkale boğazları deniz taşımacılığı açısından stratejik geçiş alanlarıdır."),
        Question(34, topic = "Tarım", text = "Türkiye'de buğday tarımının geniş alanlara yayılmasında aşağıdakilerden hangisi etkilidir?", options = listOf("Farklı iklim ve toprak koşullarına uyum sağlayabilmesi", "Yalnızca çok yağışlı kıyılarda yetişmesi", "Tuzlu deniz suyuna ihtiyaç duyması", "Sadece yüksek dağlarda yetişmesi", "Tropikal iklim istemesi"), correctIndex = 0, explanation = "Buğday farklı koşullara uyum sağlayabilen temel bir tahıldır ve Türkiye'nin birçok yerinde yetiştirilir."),
        Question(35, topic = "Tarım", text = "Türkiye'de fındık üretiminin özellikle Doğu Karadeniz'de yoğunlaşmasının temel nedeni nedir?", options = listOf("Nemli iklim ve uygun yağış koşulları", "Yıl boyunca don görülmesi", "Çöl iklimi", "Kurak ve sulamasız yazlar", "Tuzlu topraklar"), correctIndex = 0, explanation = "Fındık, nemli ve ılıman Karadeniz koşullarında özellikle kıyı kuşağında iyi gelişir."),
        Question(36, topic = "Su Varlığı", text = "Türkiye'nin en uzun akarsuyu hangisidir?", options = listOf("Kızılırmak", "Fırat", "Dicle", "Sakarya", "Meriç"), correctIndex = 0, explanation = "Kızılırmak Türkiye sınırları içinde doğup yine Türkiye sınırları içinde denize ulaşan ve ülkenin en uzun akarsuyudur.")
    )
}
