package tr.yurdunubil.app

/** Curated extra KPSS-style questions. Answer positions are intentionally mixed; SharedQuestionPool randomizes them again per session. */
object MegaQuestionBank {
    val all = listOf(
        Question(5001, topic="Coğrafi Konum", text="Türkiye'nin orta kuşakta yer alması aşağıdakilerden hangisinin oluşmasında etkilidir?", options=listOf("Mevsimlerin belirgin yaşanması", "Gelgit genliğinin çok büyük olması", "Güneş ışınlarının yıl boyunca dik gelmesi", "Muson ikliminin yaygın olması", "Kutup gecelerinin görülmesi"), correctIndex=0, explanation="Türkiye orta kuşakta olduğu için dört mevsim belirgin biçimde yaşanır."),
        Question(5002, topic="Coğrafi Konum", text="Türkiye'nin üç tarafının denizlerle çevrili olması aşağıdakilerden hangisini doğrudan etkiler?", options=listOf("Kıyı turizmi ve deniz ulaşımını", "Yerel saat farkını", "Meridyen sayısını", "Kara sınırlarının uzunluğunu", "Yükselti basamaklarını"), correctIndex=0, explanation="Denizlere kıyı; ulaşım, balıkçılık ve kıyı turizmi gibi faaliyetleri destekler."),
        Question(5003, topic="Coğrafi Konum", text="Türkiye'nin Asya ile Avrupa arasında bulunmasının en önemli jeopolitik sonuçlarından biri hangisidir?", options=listOf("Ulaşım ve enerji koridorlarında stratejik önem", "Her yerde aynı iklimin görülmesi", "Tarım alanlarının ortadan kalkması", "Akarsuların rejiminin düzenlenmesi", "Yükseltinin azalması"), correctIndex=0, explanation="Kıtalar arasındaki konum Türkiye'yi ulaşım ve enerji geçişlerinde stratejik hâle getirir."),

        Question(5004, topic="Yer Şekilleri", text="Türkiye'de yükseltinin batıdan doğuya genel olarak artmasının sonuçlarından biri hangisidir?", options=listOf("Sıcaklık ortalamalarının doğuya doğru düşmesi", "Denizlerin doğuya doğru çoğalması", "Boylam farkının azalması", "Akarsu sayısının sıfırlanması", "Kıyı uzunluğunun artması"), correctIndex=0, explanation="Yükselti arttıkça sıcaklık genel olarak azalır; bu durum doğuda karasal koşulları güçlendirir."),
        Question(5005, topic="Yer Şekilleri", text="Karstik şekillerin yaygın olduğu bir alanda aşağıdaki kayaçlardan hangisinin bulunması beklenir?", options=listOf("Kalker", "Granit", "Bazalt", "Gnays", "Şist"), correctIndex=0, explanation="Kalker, jips ve kaya tuzu gibi çözünebilen kayaçlar karstik şekillerin oluşumuna elverişlidir."),
        Question(5006, topic="Yer Şekilleri", text="Türkiye'de dağların geniş alan kaplaması aşağıdakilerden hangisini zorlaştırabilir?", options=listOf("Ulaşım ve tarım alanlarının genişlemesini", "Yükseltinin oluşmasını", "Akarsuların akmasını", "Mevsimlerin yaşanmasını", "Güneşlenmenin gerçekleşmesini"), correctIndex=0, explanation="Engebeli ve dağlık alanlarda ulaşım maliyetleri artar, tarıma uygun düz alanlar azalır."),

        Question(5007, topic="Su Varlığı", text="Akarsuların rejiminin düzensiz olması aşağıdakilerden hangisini zorlaştırır?", options=listOf("Düzenli akışa dayalı hidroelektrik üretimini", "Akarsuların vadiler oluşturmasını", "Erozyonun gerçekleşmesini", "Akarsuyun denize ulaşmasını", "Havza kavramının oluşmasını"), correctIndex=0, explanation="Debinin yıl içinde çok değişmesi suya dayalı faaliyetlerin planlanmasını güçleştirir."),
        Question(5008, topic="Su Varlığı", text="Van Gölü'nün oluşumunda aşağıdaki unsurlardan hangisi daha belirleyicidir?", options=listOf("Volkanik set oluşumu", "Delta birikimi", "Gelgit", "Mercan birikimi", "Buzul sirkleri"), correctIndex=0, explanation="Van Gölü çevresindeki volkanik faaliyetlerle oluşan setler gölün oluşumunda rol oynamıştır."),
        Question(5009, topic="Su Varlığı", text="Türkiye'de hidroelektrik potansiyelin yüksek olmasında aşağıdakilerden hangisi daha etkilidir?", options=listOf("Yükselti ve eğimin fazla olması", "Gelgitlerin güçlü olması", "Kıyıların alçak olması", "Çöl ikliminin yaygınlığı", "Akarsuların tamamen kuruması"), correctIndex=0, explanation="Yükselti farklarının ve eğimin fazla olması akarsuların enerji potansiyelini artırır."),

        Question(5010, topic="İklim ve Bitki Örtüsü", text="Akdeniz ikliminde yazların sıcak ve kurak geçmesinin doğal sonucu aşağıdakilerden hangisidir?", options=listOf("Maki topluluklarının yaygınlaşması", "Tundranın genişlemesi", "Çayırların yıl boyu gürleşmesi", "Tayga ormanlarının oluşması", "Buzulların alçalması"), correctIndex=0, explanation="Yaz kuraklığına dayanıklı maki ve benzeri Akdeniz bitkileri yaygındır."),
        Question(5011, topic="İklim ve Bitki Örtüsü", text="Karadeniz kıyılarında yıllık sıcaklık farkının iç kesimlere göre daha az olmasının temel nedeni nedir?", options=listOf("Denizelliğin sıcaklığı dengelemesi", "Boylam farkının yokluğu", "Yükseltinin çok fazla olması", "Kar yağışının hiç olmaması", "Güneş ışınlarının dik gelmesi"), correctIndex=0, explanation="Denizler geç ısınıp geç soğuduğundan kıyılarda sıcaklık farklarını azaltır."),
        Question(5012, topic="İklim ve Bitki Örtüsü", text="Yükselti arttıkça sıcaklığın azalması Türkiye'de hangi sonucu destekler?", options=listOf("Dağların üst kesimlerinde kar örtüsünün daha uzun kalmasını", "Kıyılarda don olaylarının tamamen yok olmasını", "Çöllerin her yerde oluşmasını", "Denizlerin donmasını", "Yağışın her yerde azalmasını"), correctIndex=0, explanation="Yükseltiyle sıcaklık azalır; bu nedenle yüksek alanlarda kar daha uzun süre yerde kalabilir."),

        Question(5013, topic="Nüfus ve Yerleşme", text="Nüfusun sanayi merkezlerinde yoğunlaşmasının temel nedeni aşağıdakilerden hangisidir?", options=listOf("İş olanaklarının fazla olması", "Yükseltinin her yerde düşük olması", "Yağışın her zaman fazla olması", "Tarımın tamamen yok olması", "Kıyıların düz olması"), correctIndex=0, explanation="Sanayi ve hizmetler iş olanakları oluşturarak nüfusu çeker."),
        Question(5014, topic="Nüfus ve Yerleşme", text="Türkiye'de iç göçün önemli nedenlerinden biri hangisidir?", options=listOf("Eğitim ve iş olanaklarının farklılaşması", "Meridyenlerin değişmesi", "Dağların yükselmesi", "Denizlerin tuzluluğu", "Yerel saat farkının artması"), correctIndex=0, explanation="Eğitim, istihdam ve hizmet olanakları göç kararlarında güçlü beşerî etkenlerdir."),
        Question(5015, topic="Nüfus ve Yerleşme", text="Kırsal yerleşmelerde tarımsal faaliyetlerin etkisi aşağıdakilerden hangisini daha çok belirler?", options=listOf("Yerleşme dokusu ve ekonomik faaliyetleri", "Meridyen sayısını", "Güneşlenme açısını", "Dünya'nın şekli", "Kıtaların konumunu"), correctIndex=0, explanation="Kırsal ekonominin temelinde tarım ve hayvancılık bulunduğundan yerleşme düzeni de bundan etkilenir."),

        Question(5016, topic="Tarım", text="Türkiye'de buğday tarımının geniş alanlara yayılmasında hangi özellik etkilidir?", options=listOf("Farklı iklim koşullarına belirli ölçüde uyum sağlayabilmesi", "Sadece tropikal iklim istemesi", "Don olayına tamamen dayanıksız olması", "Yalnızca kıyılarda yetişmesi", "Çok yüksek nem zorunluluğu"), correctIndex=0, explanation="Buğday farklı sıcaklık ve yağış koşullarına uyum sağlayabildiği için geniş alanda yetiştirilir."),
        Question(5017, topic="Tarım", text="Zeytin tarımının Akdeniz ve Ege kıyılarında yaygın olmasının temel nedeni hangisidir?", options=listOf("Kışların ılık geçmesi", "Yıl boyunca kar örtüsü", "Tundra iklimi", "Çok düşük yaz sıcaklıkları", "Sürekli don"), correctIndex=0, explanation="Zeytin kışların ılık geçtiği Akdeniz iklimi koşullarında daha elverişli yetişir."),
        Question(5018, topic="Tarım", text="Şeker pancarının Türkiye'de kıyı kuşağından çok iç kesimlerde yetiştirilmesinde hangi faktör önemlidir?", options=listOf("İç kesimlerin iklim ve tarım koşullarının uygunluğu", "Deniz suyunun tuzlu olması", "Gelgit", "Muson yağışları", "Kıyı akıntıları"), correctIndex=0, explanation="Şeker pancarı yaz yağışlarının ve sulama olanaklarının bulunduğu iç kesimlerde yaygın yetiştirilir."),

        Question(5019, topic="Maden ve Enerji", text="Taş kömürünün çıkarılmasıyla öne çıkan merkez aşağıdakilerden hangisidir?", options=listOf("Zonguldak", "Konya", "Antalya", "Şanlıurfa", "Muğla"), correctIndex=0, explanation="Zonguldak çevresi Türkiye'nin önemli taş kömürü sahasıdır."),
        Question(5020, topic="Maden ve Enerji", text="Bor minerallerinin Türkiye için önemli olmasının temel nedeni hangisidir?", options=listOf("Rezervlerinin zengin olması", "Sadece kıyılarda bulunması", "Petrol yerine geçmesi", "Tüm elektrik ihtiyacını karşılaması", "Yalnızca ithal edilmesi"), correctIndex=0, explanation="Türkiye dünya bor rezervlerinin önemli bölümüne sahiptir ve bor stratejik bir madendir."),
        Question(5021, topic="Maden ve Enerji", text="Jeotermal enerji potansiyelinin Ege'de yüksek olmasında hangi özellik etkilidir?", options=listOf("Fay hatlarının ve tektonik hareketliliğin fazla olması", "Kalıcı buzulların yaygınlığı", "Gelgit genliğinin büyüklüğü", "Tropikal yağışlar", "Kıyıların tamamen düz olması"), correctIndex=0, explanation="Aktif faylar yer içi sıcak suların yüzeye çıkmasını ve jeotermal potansiyeli artırır."),

        Question(5022, topic="Sanayi ve Ulaşım", text="İstanbul ve çevresinde sanayinin gelişmesinde aşağıdakilerden hangisi diğerlerine göre daha belirleyicidir?", options=listOf("Pazar, ulaşım, sermaye ve iş gücü", "Yüksek platolar", "Çok az nüfus", "Kalıcı kar örtüsü", "Çöl iklimi"), correctIndex=0, explanation="Büyük pazar, gelişmiş ulaşım ve sermaye birikimi sanayiyi destekler."),
        Question(5023, topic="Sanayi ve Ulaşım", text="Limanların gelişmesinde aşağıdakilerden hangisi doğrudan önem taşır?", options=listOf("Hinterlandın genişliği ve ulaşım bağlantıları", "Meridyen sayısı", "Yükseltinin tek başına fazla olması", "Kar yağışının sürekli olması", "Yerel saat farkı"), correctIndex=0, explanation="Limanın hinterlandı ve kara-demir yolu bağlantıları ticaret kapasitesini artırır."),
        Question(5024, topic="Sanayi ve Ulaşım", text="Türkiye'de kara yolu ulaşımının gelişmesinde dağlık yapı neden önemlidir?", options=listOf("Geçit ve tünel ihtiyacını artırması", "Deniz seviyesini yükseltmesi", "Meridyenleri azaltması", "Akarsuları durdurması", "İklimi tamamen değiştirmesi"), correctIndex=0, explanation="Dağlık ve engebeli alanlarda ulaşım güzergâhları geçit ve tünellerden yararlanır."),

        Question(5025, topic="Turizm", text="Pamukkale'nin turizm değerinde aşağıdakilerden hangisi öne çıkar?", options=listOf("Travertenler ve termal kaynaklar", "Taş kömürü yatakları", "Geniş delta ovaları", "Buzul vadileri", "Çöl kumulları"), correctIndex=0, explanation="Pamukkale travertenleri ve termal suları doğal turizm değeridir."),
        Question(5026, topic="Turizm", text="Türkiye'de kıyı turizminin özellikle güney ve batı kıyılarında gelişmesinde hangi faktör önemlidir?", options=listOf("Ilıman iklim ve uzun yaz sezonu", "Yıl boyu don", "Tundra bitkileri", "Kalıcı kar", "Çok kısa gündüzler"), correctIndex=0, explanation="Akdeniz ve Ege kıyılarında sıcak ve uzun yaz dönemi deniz turizmini destekler."),
        Question(5027, topic="Turizm", text="Kapadokya'nın kültür turizmi açısından öne çıkmasında hangi unsur önemlidir?", options=listOf("Peri bacaları ve kaya yerleşmeleri", "Taş kömürü havzaları", "Geniş delta ovaları", "Kıyı lagünleri", "Muson ormanları"), correctIndex=0, explanation="Volkanik tüflerin aşınmasıyla oluşan peri bacaları ve tarihî kaya yerleşmeleri bölgeyi özgün kılar."),

        Question(5028, topic="Bölgeler", text="Marmara Bölgesi'nin nüfus yoğunluğunun yüksek olmasında hangisi daha etkilidir?", options=listOf("Sanayi ve hizmetlerin gelişmiş olması", "Yükseltinin en fazla olması", "Çöl iklimi", "Tarımın tamamen yokluğu", "Kalıcı buzullar"), correctIndex=0, explanation="Sanayi, ticaret, ulaşım ve hizmetler Marmara'da güçlü bir nüfus çekimi oluşturur."),
        Question(5029, topic="Bölgeler", text="Doğu Anadolu Bölgesi'nde nüfus yoğunluğunun genel olarak düşük olmasının nedenlerinden biri hangisidir?", options=listOf("Yükselti ve engebeliliğin fazla olması", "Sanayinin ülke ortalamasından çok yüksek olması", "Denize kıyının çok uzun olması", "Kışların çok ılık olması", "Tarım sezonunun çok uzun olması"), correctIndex=0, explanation="Yüksek ve engebeli arazi ile sert iklim yerleşme ve ekonomik faaliyetleri sınırlar."),
        Question(5030, topic="Bölgeler", text="Güneydoğu Anadolu'da sulama yatırımlarının artması aşağıdakilerden hangisini doğrudan destekler?", options=listOf("Tarımsal üretim çeşitliliğinin artmasını", "Karadeniz ormanlarının genişlemesini", "Kıyı turizminin sona ermesini", "Yükseltinin azalmasını", "Depremlerin durmasını"), correctIndex=0, explanation="Sulama, kurak koşulların etkisini azaltarak ürün desenini ve tarımsal verimi artırabilir."),

        Question(5031, topic="Doğal Afetler", text="Karadeniz'in eğimli yamaçlarında heyelan riskinin yüksek olmasında hangileri birlikte etkilidir?", options=listOf("Fazla yağış ve eğimli arazi", "Kuraklık ve düzlük", "Çöl iklimi ve düşük eğim", "Gelgit ve mercanlar", "Kalıcı buzullar ve kuraklık"), correctIndex=0, explanation="Yoğun yağış zemini suya doyurur; eğimli yamaçlar da kütle hareketlerini kolaylaştırır."),
        Question(5032, topic="Doğal Afetler", text="Türkiye'de deprem riskinin yüksek olmasının temel nedeni hangisidir?", options=listOf("Aktif fay hatlarının bulunması", "Orta kuşakta yer alması", "Üç tarafının denizlerle çevrili olması", "Tarım alanlarının genişliği", "Liman sayısının fazla olması"), correctIndex=0, explanation="Türkiye aktif tektonik kuşak üzerinde bulunduğundan birçok diri fay sistemine sahiptir."),
        Question(5033, topic="Doğal Afetler", text="Bitki örtüsünün zayıf olduğu eğimli arazilerde erozyonun artmasında hangisi etkilidir?", options=listOf("Bitki köklerinin toprağı tutamaması", "Nem oranının her zaman sıfır olması", "Deniz seviyesinin yükselmesi", "Meridyenlerin azalması", "Gelgitin artması"), correctIndex=0, explanation="Bitki örtüsü toprağı kökleriyle tutar; zayıflaması yüzey akışını ve erozyonu artırabilir."),

        Question(5034, topic="Harita Bilgisi", text="1/200.000 ölçekli bir harita ile 1/500.000 ölçekli bir harita karşılaştırıldığında hangisi doğrudur?", options=listOf("1/200.000 daha büyük ölçeklidir ve daha ayrıntılıdır", "1/500.000 daha büyük ölçeklidir", "İkisinin ayrıntısı aynıdır", "Küçük ölçekli harita daha fazla ayrıntı verir", "Ölçek yalnızca renkleri belirler"), correctIndex=0, explanation="Payda küçüldükçe ölçek büyür; büyük ölçekli haritalar daha fazla ayrıntı gösterir."),
        Question(5035, topic="Harita Bilgisi", text="İzohipslerin sıklaştığı bir yerde aşağıdakilerden hangisi söylenebilir?", options=listOf("Eğim fazladır", "Eğim sıfırdır", "Arazi kesinlikle denizdir", "Yükselti bilinemez", "Yağış mutlaka fazladır"), correctIndex=0, explanation="İzohipsler birbirine yaklaştıkça yükselti kısa mesafede hızlı değişir ve eğim artar."),
        Question(5036, topic="Harita Bilgisi", text="Bir haritada kuzey yönünü belirlemek için en temel araçlardan biri hangisidir?", options=listOf("Yön oku", "İzohips aralığı", "Lejant rengi", "Ölçek çubuğu", "Profil çizgisi"), correctIndex=0, explanation="Yön oku haritanın yönlendirilmesinde doğrudan kullanılır."),
    )
}
