package tr.yurdunubil.app

/**
 * Curated questions extracted from the visual pages of kpss coğrafya not.pdf.
 * The source PDF is 39 pages; this bank focuses on high-yield map-reading and
 * direct knowledge points rather than copying every handwritten note verbatim.
 */
object PdfCuratedQuestionBank {
    val all = listOf(
        Question(14001, "Coğrafi Konum", "PDF'deki şemaya göre Türkiye'nin kuzey-güney matematiksel konumu hangi paralel aralığıdır?", listOf("26°-42° Kuzey", "36°-45° Kuzey", "26°-45° Kuzey", "30°-42° Kuzey"), 0, "Kaynak: kpss coğrafya not.pdf, s. 3."),
        Question(14002, "Coğrafi Konum", "PDF'deki şemaya göre Türkiye'nin doğu-batı matematiksel konumu hangi meridyen aralığıdır?", listOf("30°-45° Doğu", "26°-45° Doğu", "26°-42° Doğu", "36°-45° Doğu"), 1, "Kaynak: kpss coğrafya not.pdf, s. 3."),
        Question(14003, "Coğrafi Konum", "PDF'deki nota göre aynı meridyen üzerindeki merkezlerde ortak olan temel özellik hangisidir?", listOf("Yerel saat", "Güneş ışınlarının geliş açısı", "Yağış miktarı", "Yükselti"), 0, "Kaynak: kpss coğrafya not.pdf, s. 3."),
        Question(14004, "Coğrafi Konum", "PDF'deki nota göre aynı enlem üzerindeki merkezlerde ortak kabul edilen özellik hangisidir?", listOf("Yerel saat", "Güneş ışınlarının geliş açısı", "Boylam farkı", "Deniz seviyesine uzaklık"), 1, "Kaynak: kpss coğrafya not.pdf, s. 3."),
        Question(14005, "Coğrafi Konum", "PDF'de Türkiye'nin güneyinde 36° kuzey paraleli, kuzeyinde ise hangi paralel gösterilmiştir?", listOf("42° Kuzey", "45° Kuzey", "26° Kuzey", "30° Kuzey"), 0, "Kaynak: kpss coğrafya not.pdf, s. 3."),
        Question(14006, "Yer Şekilleri", "PDF'de Türkiye'nin kırık dağları haritasında dağların genel uzanışını çalışmak için hangi bilgi grubu öne çıkarılmıştır?", listOf("Kırık dağlar", "Volkanik dağlar", "Kıyı ovaları", "Karstik platolar"), 0, "Kaynak: kpss coğrafya not.pdf, s. 6."),
        Question(14007, "Yer Şekilleri", "PDF'de volkanik dağlar haritasında aşağıdakilerden hangisi yer alır?", listOf("Ağrı", "Küre", "Yıldız", "Samanlı"), 0, "Kaynak: kpss coğrafya not.pdf, s. 6."),
        Question(14008, "Su Varlığı", "PDF'deki göller haritasında oluşumlarına göre hangi göl grupları birlikte gösterilmiştir?", listOf("Tektonik, karstik, volkanik ve buzul", "Sadece tektonik ve karstik", "Sadece set ve volkanik", "Sadece buzul ve kıyı"), 0, "Kaynak: kpss coğrafya not.pdf, s. 9."),
        Question(14009, "Su Varlığı", "PDF'de göllerin oluşum sınıflandırmasında Van Gölü hangi başlıkla birlikte anılmıştır?", listOf("Volkanik", "Buzul", "Karstik", "Alüvyal"), 0, "Kaynak: kpss coğrafya not.pdf, s. 9."),
        Question(14010, "Su Varlığı", "PDF'deki set gölleri haritasında aşağıdakilerden hangisi bir set gölü türü olarak gösterilmiştir?", listOf("Heyelan set", "Buzul set", "Mercan set", "Moren set"), 0, "Kaynak: kpss coğrafya not.pdf, s. 9."),
        Question(14011, "Doğal Afetler", "PDF'deki deprem haritasında Türkiye'deki temel deprem grupları nasıl ayrılmıştır?", listOf("Çöküntü ve tektonik", "Volkanik ve buzul", "Karstik ve kıyı", "Delta ve rüzgâr"), 0, "Kaynak: kpss coğrafya not.pdf, s. 10."),
        Question(14012, "Doğal Afetler", "PDF'deki deprem notuna göre heyelanların en fazla görüldüğü bölge hangisidir?", listOf("Karadeniz", "İç Anadolu", "Güneydoğu Anadolu", "Ege"), 0, "Kaynak: kpss coğrafya not.pdf, s. 10."),
        Question(14013, "Yer Şekilleri", "PDF'deki karstik şekiller bölümünde özellikle hangi kayaçlar vurgulanmıştır?", listOf("Kireç taşı ve jips", "Granit ve bazalt", "Gnays ve şist", "Andezit ve tüf"), 0, "Kaynak: kpss coğrafya not.pdf, s. 11."),
        Question(14014, "Yer Şekilleri", "PDF'de tombolo hangi oluşum süreciyle ilişkilendirilmiştir?", listOf("Dalga biriktirmesi", "Akarsu aşındırması", "Rüzgâr aşındırması", "Buzul aşındırması"), 0, "Kaynak: kpss coğrafya not.pdf, s. 11."),
        Question(14015, "Kıyı Tipleri", "PDF'deki kıyı tipleri haritasında Türkiye için aşağıdakilerden hangisi gösterilmiştir?", listOf("Boyuna kıyı", "Fiyortlu kıyı", "Skayer kıyı", "Haliçli kıyı"), 0, "Kaynak: kpss coğrafya not.pdf, s. 12."),
        Question(14016, "Kıyı Tipleri", "PDF'de Türkiye'nin kıyı şekilleri çalışmasında aşağıdakilerden hangisi ayrı başlıkla verilmiştir?", listOf("Körfezler", "Mercan resifleri", "Fiyortlar", "Skayerler"), 0, "Kaynak: kpss coğrafya not.pdf, s. 12."),
        Question(14017, "Tarım", "PDF'deki tarım notuna göre buğday üretiminde öne çıkan il hangisidir?", listOf("Konya", "Rize", "Antalya", "Mersin"), 0, "Kaynak: kpss coğrafya not.pdf, s. 14."),
        Question(14018, "Tarım", "PDF'deki tarım notuna göre mısır için özellikle hangi iki bölgesel özellik vurgulanmıştır?", listOf("Karadeniz ve Çukurova", "Ergene ve Tuz Gölü", "Konya ve Erzurum", "Harran ve Gediz"), 0, "Kaynak: kpss coğrafya not.pdf, s. 14."),
        Question(14019, "Tarım", "PDF'deki notta pirinç üretimi için öne çıkarılan il hangisidir?", listOf("Edirne", "Konya", "Rize", "Kayseri"), 0, "Kaynak: kpss coğrafya not.pdf, s. 15."),
        Question(14020, "Tarım", "PDF'deki nota göre çay üretimi hangi il ile eşleştirilmiştir?", listOf("Rize", "Mersin", "Konya", "Manisa"), 0, "Kaynak: kpss coğrafya not.pdf, s. 15."),
        Question(14021, "Tarım", "PDF'deki nota göre şeker pancarı için öne çıkarılan il hangisidir?", listOf("Konya", "Adana", "Rize", "Antalya"), 0, "Kaynak: kpss coğrafya not.pdf, s. 15."),
        Question(14022, "Tarım", "PDF'deki nota göre zeytin üretimiyle eşleştirilen merkezlerden biri hangisidir?", listOf("Mardin", "Rize", "Kars", "Van"), 0, "Kaynak: kpss coğrafya not.pdf, s. 15."),
        Question(14023, "Tarım", "PDF'deki nota göre incir için verilen il hangisidir?", listOf("Aydın", "Erzurum", "Konya", "Van"), 0, "Kaynak: kpss coğrafya not.pdf, s. 15."),
        Question(14024, "Tarım", "PDF'deki nota göre üzüm üretimiyle eşleştirilen il hangisidir?", listOf("Manisa", "Rize", "Kars", "Mersin"), 0, "Kaynak: kpss coğrafya not.pdf, s. 15."),
        Question(14025, "Hayvancılık", "PDF'deki hayvancılık haritasında koyun yetiştiriciliği için öne çıkan merkezlerden biri hangisidir?", listOf("Konya", "Rize", "Antalya", "Muğla"), 0, "Kaynak: kpss coğrafya not.pdf, s. 16."),
        Question(14026, "Hayvancılık", "PDF'deki hayvancılık notuna göre kıl keçisi için verilen merkezlerden biri hangisidir?", listOf("Mersin", "Ankara", "Kars", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 16."),
        Question(14027, "Hayvancılık", "PDF'deki hayvancılık notuna göre tiftik keçisi için öne çıkan il hangisidir?", listOf("Ankara", "Mersin", "İzmir", "Bursa"), 0, "Kaynak: kpss coğrafya not.pdf, s. 16."),
        Question(14028, "Hayvancılık", "PDF'deki hayvancılık notuna göre arıcılık için verilen merkezlerden biri hangisidir?", listOf("Ordu", "Konya", "Şanlıurfa", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 16."),
        Question(14029, "Maden ve Enerji", "PDF'deki maden haritasında demir yataklarından biri hangi il ile eşleştirilmiştir?", listOf("Sivas", "Rize", "Muğla", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 17."),
        Question(14030, "Maden ve Enerji", "PDF'deki krom haritasında krom yataklarıyla ilişkilendirilen merkezlerden biri hangisidir?", listOf("Elazığ", "Konya", "Rize", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 17."),
        Question(14031, "Maden ve Enerji", "PDF'deki bakır haritasında bakır yataklarıyla ilişkilendirilen merkezlerden biri hangisidir?", listOf("Artvin", "Konya", "Antalya", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 17."),
        Question(14032, "Maden ve Enerji", "PDF'de boksit için verilen merkez hangisidir?", listOf("Seydişehir", "Zonguldak", "Artvin", "Erzurum"), 0, "Kaynak: kpss coğrafya not.pdf, s. 18."),
        Question(14033, "Maden ve Enerji", "PDF'de bor için verilen merkezlerden biri hangisidir?", listOf("Kırka", "Rize", "Kars", "Mardin"), 0, "Kaynak: kpss coğrafya not.pdf, s. 18."),
        Question(14034, "Maden ve Enerji", "PDF'de fosfat hangi il ile ilişkilendirilmiştir?", listOf("Mardin", "Rize", "Konya", "Bursa"), 0, "Kaynak: kpss coğrafya not.pdf, s. 18."),
        Question(14035, "Maden ve Enerji", "PDF'de cıva için verilen merkezlerden biri hangisidir?", listOf("Konya", "Rize", "Kars", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 18."),
        Question(14036, "Maden ve Enerji", "PDF'de kükürt hangi merkezle ilişkilendirilmiştir?", listOf("Keçiborlu", "Seydişehir", "Kırka", "Artvin"), 0, "Kaynak: kpss coğrafya not.pdf, s. 19."),
        Question(14037, "Maden ve Enerji", "PDF'de manganez için verilen merkezlerden biri hangisidir?", listOf("Artvin", "Rize", "Konya", "Edirne"), 0, "Kaynak: kpss coğrafya not.pdf, s. 19."),
        Question(14038, "Maden ve Enerji", "PDF'deki taş kömürü notunda oluşum zamanı hangi jeolojik dönemle ilişkilendirilmiştir?", listOf("Karbonifer", "Kretase", "Jura", "Kuaterner"), 0, "Kaynak: kpss coğrafya not.pdf, s. 23."),
        Question(14039, "Maden ve Enerji", "PDF'de linyit için 'en geniş alanda bulunan' ifadesi hangi kaynakla ilişkilendirilmiştir?", listOf("Linyit", "Taş kömürü", "Bor", "Petrol"), 0, "Kaynak: kpss coğrafya not.pdf, s. 24."),
        Question(14040, "Maden ve Enerji", "PDF'deki petrol haritasında Batman çevresi hangi enerji kaynağıyla ilişkilendirilmiştir?", listOf("Petrol", "Bor", "Demir", "Krom"), 0, "Kaynak: kpss coğrafya not.pdf, s. 24."),
        Question(14041, "Maden ve Enerji", "PDF'de jeotermal enerji haritasında yoğunlaşmanın özellikle hangi bölgede gösterildiği görülür?", listOf("Batı Anadolu", "Doğu Karadeniz", "Kuzeydoğu Anadolu", "Güneydoğu Anadolu"), 0, "Kaynak: kpss coğrafya not.pdf, s. 25."),
        Question(14042, "Maden ve Enerji", "PDF'deki güneş enerjisi haritasında aşağıdakilerden hangisi merkez olarak gösterilmiştir?", listOf("Konya", "Rize", "Artvin", "Zonguldak"), 0, "Kaynak: kpss coğrafya not.pdf, s. 26."),
        Question(14043, "Sanayi ve Ulaşım", "PDF'de demir-çelik endüstrisi için verilen merkezlerden biri hangisidir?", listOf("Zonguldak", "Rize", "Konya", "Antalya"), 0, "Kaynak: kpss coğrafya not.pdf, s. 28."),
        Question(14044, "Sanayi ve Ulaşım", "PDF'de boksit endüstrisi hangi merkezle eşleştirilmiştir?", listOf("Seydişehir", "İzmit", "Rize", "Mardin"), 0, "Kaynak: kpss coğrafya not.pdf, s. 28."),
        Question(14045, "Sanayi ve Ulaşım", "PDF'de otomotiv endüstrisi merkezlerinden biri hangisidir?", listOf("Bursa", "Rize", "Van", "Kars"), 0, "Kaynak: kpss coğrafya not.pdf, s. 29."),
        Question(14046, "Sanayi ve Ulaşım", "PDF'de kağıt endüstrisi merkezlerinden biri hangisidir?", listOf("İzmit", "Rize", "Van", "Mardin"), 0, "Kaynak: kpss coğrafya not.pdf, s. 29."),
        Question(14047, "Sanayi ve Ulaşım", "PDF'de cam endüstrisi merkezlerinden biri hangisidir?", listOf("Kırklareli", "Rize", "Kars", "Van"), 0, "Kaynak: kpss coğrafya not.pdf, s. 30."),
        Question(14048, "Bölgeler", "PDF'deki bölgesel kalkınma projeleri haritasında KOP kısaltması hangi projeyi ifade eder?", listOf("Konya Ovası Projesi", "Doğu Anadolu Projesi", "Doğu Karadeniz Projesi", "Güneydoğu Anadolu Projesi"), 0, "Kaynak: kpss coğrafya not.pdf, s. 34."),
        Question(14049, "Bölgeler", "PDF'deki bölgesel kalkınma projeleri haritasında DOKAP hangi projedir?", listOf("Doğu Karadeniz Projesi", "Doğu Anadolu Projesi", "Konya Ovası Projesi", "Yeşilırmak Havzası Gelişim Projesi"), 0, "Kaynak: kpss coğrafya not.pdf, s. 34."),
        Question(14050, "Bölgeler", "PDF'deki bölgesel kalkınma projeleri haritasında YHGP hangi havzayla ilişkilidir?", listOf("Yeşilırmak", "Fırat", "Dicle", "Sakarya"), 0, "Kaynak: kpss coğrafya not.pdf, s. 35."),
        Question(14051, "Turizm", "PDF'deki Cittaslow listesinde İzmir hangi yerlerle eşleştirilmiştir?", listOf("Seferihisar ve Foça", "Şarköy ve Gerze", "Halfeti ve Gökçeada", "İznik ve Safranbolu"), 0, "Kaynak: kpss coğrafya not.pdf, s. 33."),
        Question(14052, "Turizm", "PDF'deki Cittaslow listesinde Tekirdağ hangi yerle eşleştirilmiştir?", listOf("Şarköy", "Gerze", "Halfeti", "Foça"), 0, "Kaynak: kpss coğrafya not.pdf, s. 33."),
        Question(14053, "Turizm", "PDF'deki Cittaslow listesinde Çanakkale hangi yerle eşleştirilmiştir?", listOf("Gökçeada", "Şarköy", "Gerze", "Halfeti"), 0, "Kaynak: kpss coğrafya not.pdf, s. 33."),
        Question(14054, "Turizm", "PDF'deki UNESCO tablosu ağırlıklı olarak hangi tür bilgileri eşleştirir?", listOf("İl ve kültürel/doğal miras alanı", "İl ve maden yatağı", "İl ve tarım ürünü", "İl ve sanayi tesisi"), 0, "Kaynak: kpss coğrafya not.pdf, s. 36-38."),
        Question(14055, "Turizm", "PDF'deki UNESCO örnekleri arasında aşağıdakilerden hangisi yer almaktadır?", listOf("Nemrut Dağı", "Tuz Gölü", "Kızılırmak Deltası", "Konya Ovası"), 0, "Kaynak: kpss coğrafya not.pdf, s. 36."),
        Question(14056, "Ulaşım", "PDF'nin son sayfasındaki ekspres tren rotaları içinde Zonguldak-Karabük hattıyla ilişkilendirilen ekspres hangisidir?", listOf("Karaelmas Ekspresi", "Göller Ekspresi", "Toros Ekspresi", "Van Gölü Ekspresi"), 0, "Kaynak: kpss coğrafya not.pdf, s. 39."),
        Question(14057, "Ulaşım", "PDF'nin son sayfasına göre Göller Ekspresi hangi şehirlerden geçer?", listOf("İzmir-Aydın-Denizli-Burdur-Isparta", "Ankara-Kayseri-Sivas-Erzincan-Kars", "Konya-Karaman-Ulukışla-Adana", "Ankara-Kayseri-Malatya-Elazığ-Bingöl"), 0, "Kaynak: kpss coğrafya not.pdf, s. 39."),
        Question(14058, "Ulaşım", "PDF'nin son sayfasına göre Toros Ekspresi rotasında aşağıdakilerden hangisi yer alır?", listOf("Konya", "Rize", "Artvin", "Kars"), 0, "Kaynak: kpss coğrafya not.pdf, s. 39."),
        Question(14059, "Ulaşım", "PDF'nin son sayfasına göre Van Gölü Ekspresi rotasında aşağıdakilerden hangisi yer alır?", listOf("Ankara", "İzmir", "Adana", "Antalya"), 0, "Kaynak: kpss coğrafya not.pdf, s. 39."),
        Question(14060, "Bölgeler", "PDF'de bölgesel kalkınma projeleri haritasında GAP hangi kısaltmayla gösterilmiştir?", listOf("GAP", "DAP", "KOP", "DOKAP"), 0, "Kaynak: kpss coğrafya not.pdf, s. 34.")
    )
}
