package tr.yurdunubil.app

/**
 * Source-derived KPSS Geography material prepared from the user-provided
 * geography PDFs. Content is paraphrased/restructured rather than copied.
 * The bank intentionally focuses on map-reading, relationships and exam-style inference.
 */
object SourceDerivedGeographyBank {
    val all: List<Question> = listOf(
        Question(3001, "Coğrafi Konum", "Türkiye'nin 26°-45° doğu meridyenleri arasında bulunması hangi sonuca doğrudan yol açar?", listOf("Doğu-batı arasında yerel saat farkı oluşmasına", "Dört mevsimin yaşanmasına", "Güneş ışınlarının dik gelmesine", "Dağların doğu-batı uzanmasına", "Karstik şekillerin yaygınlaşmasına"), 0, "Meridyen farkı yerel saat farkını belirler; Türkiye'nin doğusu batısına göre daha ileridir."),
        Question(3002, "Coğrafi Konum", "Türkiye'nin 36°-42° kuzey paralelleri arasında yer almasının sonuçlarından biri hangisidir?", listOf("Güneş ışınlarının yıl içinde hiçbir zaman dik gelmemesi", "Yerel saat farkının 76 dakika olması", "Boğazların bulunması", "Transit ticaretin gelişmesi", "Petrol boru hatlarının geçmesi"), 0, "Türkiye Yengeç Dönencesi'nin kuzeyinde ve orta kuşakta olduğundan Güneş ışınları dik açıyla gelmez."),
        Question(3003, "Coğrafi Konum", "Türkiye'de güney yamaçların kuzey yamaçlara göre daha fazla ısınması hangi faktörle açıklanır?", listOf("Bakı", "Boylam", "Yerel saat", "Gelgit", "Kıyı tipi"), 0, "Kuzey Yarım Küre'de Güneş ışınları genel olarak güney yamaçlara daha elverişli açıyla gelir."),
        Question(3004, "Coğrafi Konum", "Aynı enlem üzerinde bulunan iki merkezde sıcaklıkların belirgin biçimde farklı olması aşağıdakilerden hangisinin etkisini düşündürür?", listOf("Yükselti veya denizellik-karasallık", "Meridyenlerin eşitliği", "Ekvator'a uzaklığın değişmesi", "Paralel uzunluğunun değişmesi", "Ulusal saat"), 0, "Aynı enlem, matematik konumu benzer kılar; yükselti ve denize uzaklık gibi özel konum özellikleri sıcaklığı değiştirebilir."),
        Question(3005, "Coğrafi Konum", "Türkiye'nin Asya ile Avrupa arasında bulunması aşağıdakilerden hangisini güçlendiren temel özel konum özelliklerindendir?", listOf("Transit ulaşım ve ticaret", "Gelgit genliğinin artması", "Buzul vadilerinin oluşması", "Güneş ışınlarının dikleşmesi", "Paraleller arası mesafenin azalması"), 0, "Kıtalar arasındaki geçiş konumu ulaşım ve transit ticaret açısından stratejik önem sağlar."),

        Question(3011, "Yer Şekilleri", "Ege kıyılarında dağların kıyıya dik uzanması aşağıdakilerden hangisini kolaylaştırır?", listOf("Denizin iç kesimlere sokulmasını", "Kıyı ile iç kesim arasında ulaşımın tamamen kesilmesini", "Kıyıların sürekli falezli olmasını", "Kalıcı kar sınırının düşmesini", "Gelgit etkisinin artmasını"), 0, "Vadilerin denize doğru açılması kıyının girintili-çıkıntılı olmasına ve denizin içeri sokulmasına ortam hazırlar."),
        Question(3012, "Yer Şekilleri", "Türkiye'nin genç ve engebeli arazi yapısının bir sonucu olarak gerçek alan ile izdüşüm alan arasındaki farkın fazla olması aşağıdakilerden hangisini gösterir?", listOf("Yüzeyin yatay düzleme göre daha engebeli olduğunu", "Ülkenin daha geniş bir enlem aralığında bulunduğunu", "Yerel saat farkının arttığını", "Kıyıların tamamının delta olduğunu", "Yağışın ülke genelinde eşit olduğunu"), 0, "Engebeli arazide yüzey alanı, aynı alanın yatay izdüşümünden daha büyüktür."),
        Question(3013, "Yer Şekilleri", "Kalkerli arazilerde yer altı sularının çözündürme etkisiyle oluşan en küçük karstik şekil hangisidir?", listOf("Lapya", "Polye", "Uvala", "Obruk", "Traverten"), 0, "Lapya, kalker yüzeyindeki küçük oluk ve çukurlardan oluşan en küçük karstik çözünme şeklidir."),
        Question(3014, "Yer Şekilleri", "Dolinlerin birleşmesiyle oluşan daha büyük karstik çukurlara ne ad verilir?", listOf("Uvala", "Lapya", "Düden", "Sarkıt", "Moren"), 0, "Karstik şekillerin büyüme sıralamasında dolinlerin birleşmesi uvalayı oluşturur."),
        Question(3015, "Yer Şekilleri", "Karstik alanlarda yer altı boşluklarının tavanının çökmesiyle oluşabilen derin çukurluk hangisidir?", listOf("Obruk", "Taraça", "Menderes", "Kumul", "Hörgüç kaya"), 0, "Obruk, karstik çözünme sonucu gelişen yer altı boşluklarının çökmesiyle oluşabilir."),
        Question(3016, "Yer Şekilleri", "Mağara tavanından aşağı doğru büyüyen karstik birikim şekli hangisidir?", listOf("Sarkıt", "Dikit", "Sütun", "Traverten", "Polye"), 0, "Sarkıt tavandan aşağı sarkar; dikit tabandan yukarı doğru gelişir."),
        Question(3017, "Yer Şekilleri", "Akarsu eğiminin azaldığı alanlarda yatağın genişlemesi ve kıvrımların belirginleşmesi hangi şeklin gelişimini destekler?", listOf("Menderes", "Çentik vadi", "Boğaz vadi", "Sirk çukuru", "Mantar kaya"), 0, "Eğim azaldığında akarsuyun yana aşındırması ve biriktirmesi artar; menderesler belirginleşir."),
        Question(3018, "Yer Şekilleri", "Çukurova, Bafra ve Çarşamba ovalarının ortak oluşum süreci aşağıdakilerden hangisidir?", listOf("Akarsu biriktirmesi", "Buzul aşındırması", "Rüzgâr aşındırması", "Volkanik püskürme", "Dalga aşındırması"), 0, "Bu ovalar akarsuların taşıdığı alüvyonların kıyıda birikmesiyle oluşan delta ovalarıdır."),
        Question(3019, "Yer Şekilleri", "Rüzgâr aşındırmasının etkili olabilmesi için aşağıdaki koşullardan hangisinin birlikte bulunması daha uygundur?", listOf("Kuraklık, seyrek bitki örtüsü ve gevşek malzeme", "Sürekli yağış ve gür orman", "Kalın buz örtüsü ve yüksek nem", "Yoğun nüfus ve sanayi", "Gelgit ve mercan resifleri"), 0, "Kurak-yarı kurak ortamlar ve bitki örtüsünün zayıflığı yüzey malzemesinin rüzgârla taşınmasını kolaylaştırır."),
        Question(3020, "Yer Şekilleri", "Aşağıdakilerden hangisi Türkiye'de yüksek dağlarda görülebilen buzul aşındırma şekillerinden biridir?", listOf("Sirk çukuru", "Delta ovası", "Kumul", "Tombolo", "Birikinti konisi"), 0, "Sirk çukurları yüksek dağlarda buzulların aşındırmasıyla oluşur."),
        Question(3021, "Yer Şekilleri", "Buzulların taşıyıp biriktirdiği malzemeye verilen ad hangisidir?", listOf("Moren", "Lös", "Alüvyon", "Traverten", "Taraça"), 0, "Moren, buzul tarafından taşınan ve biriktirilen malzemeyi ifade eder."),
        Question(3022, "Yer Şekilleri", "Türkiye'de fiyort kıyılarının bulunmamasında aşağıdakilerden hangisi temel açıklamadır?", listOf("Buzulların deniz seviyesine kadar etkili olmaması", "Kıyıların çok girintili olması", "Gelgitin fazla olması", "Mercanların gelişmesi", "Akarsuların kısa olması"), 0, "Fiyort için buzul vadilerinin deniz tarafından basılması gerekir; Türkiye'deki buzullaşma bu koşulu sağlamaz."),
        Question(3023, "Yer Şekilleri", "Finike-Kaş arasındaki kıyılarda görülen Dalmaçya kıyı tipi hangi oluşum özelliğiyle ilişkilidir?", listOf("Kıyıya paralel dağ sıralarının alçak kesimlerinin sular altında kalması", "Akarsu vadilerinin tamamen dolması", "Mercanların set oluşturması", "Buzul vadilerinin denizle dolması", "Gelgit düzlüklerinin oluşması"), 0, "Dalmaçya kıyısında kıyıya paralel dağların alçak kesimleri deniz altında kalırken yüksek kesimler ada olarak kalır."),

        Question(3031, "İklim ve Bitki Örtüsü", "Karadeniz kıyılarında ormanların geniş alan kaplamasında aşağıdakilerden hangisi temel etkendir?", listOf("Nemli koşulların ve yağışın fazla olması", "Yaz kuraklığının çok şiddetli olması", "Çöl koşullarının bulunması", "Kalıcı donun yaygınlığı", "Yağışın yalnızca kışın düşmesi"), 0, "Nemli iklim koşulları orman gelişimi için elverişlidir."),
        Question(3032, "İklim ve Bitki Örtüsü", "Türkiye'de Akdeniz kıyılarının yaz aylarında belirgin biçimde kuraklaşmasında hangi basınç merkezi etkili olur?", listOf("Asor Dinamik Yüksek Basıncı", "İzlanda Dinamik Alçak Basıncı", "Sibirya Termik Yüksek Basıncı", "Basra Termik Yüksek Basıncı", "Ekvatoral Alçak Basınç"), 0, "Asor yüksek basıncı yazın Akdeniz çevresinde yükselici hareketi baskılar ve yağışları azaltır."),
        Question(3033, "İklim ve Bitki Örtüsü", "Kışın Türkiye'ye soğuk ve sert hava getiren basınç merkezi hangisidir?", listOf("Sibirya Termik Yüksek Basıncı", "Asor Dinamik Yüksek Basıncı", "İzlanda Dinamik Alçak Basıncı", "Basra Termik Alçak Basıncı", "Ekvatoral Yüksek Basınç"), 0, "Sibirya termik yüksek basıncı kışın Türkiye'yi etkileyerek soğuk hava taşır."),
        Question(3034, "İklim ve Bitki Örtüsü", "İç kesimlerde kıyılara göre yıllık sıcaklık farkının daha fazla olması hangi özelliğin göstergesidir?", listOf("Karasallık", "Denizellik", "Bakı", "Boylam", "Gelgit"), 0, "Denizlerin ılımanlaştırıcı etkisinin azalması sıcaklık farklarını artırır."),
        Question(3035, "İklim ve Bitki Örtüsü", "Bir bölgede küçük bir alanın çevresinden farklı iklim özellikleri göstermesi hangi kavramla açıklanır?", listOf("Mikroklima", "Makroklima", "Mutlak konum", "Bakı", "Yerel saat"), 0, "Mikroklima, daha geniş iklim alanı içinde çevresinden farklılaşan küçük alanlardaki özel koşullardır."),

        Question(3041, "Su Varlığı", "Türkiye'deki akarsuların rejimlerinin çoğunlukla düzensiz olmasının temel nedenlerinden biri hangisidir?", listOf("Yağışın yıl içindeki dağılışının değişken olması", "Ülkenin tamamen düz olması", "Gelgitin güçlü olması", "Akarsuların hepsinin yer altından akması", "Tüm bölgelerde aynı iklimin görülmesi"), 0, "Yağış rejimindeki mevsimsel farklılıklar akarsu debilerinin yıl içinde değişmesine yol açar."),
        Question(3042, "Su Varlığı", "Baraj göllerinin oluşturulmasında aşağıdakilerden hangisi amaçlardan biri değildir?", listOf("Sulama", "Hidroelektrik üretimi", "İçme suyu sağlama", "Taşkın kontrolü", "Gelgit oluşturma"), 4, "Baraj gölleri sulama, enerji, içme suyu ve taşkın kontrolü gibi amaçlarla kullanılır; gelgit oluşturmaz."),
        Question(3043, "Su Varlığı", "Fırat ve Dicle'nin Güneydoğu Anadolu açısından ortak önemi aşağıdakilerden hangisidir?", listOf("Sulama ve hidroelektrik potansiyel sağlamaları", "Karadeniz'e dökülmeleri", "Tamamının Türkiye içinde doğup bitmesi", "Marmara'dan geçmeleri", "Rejimlerinin yıl boyunca sabit olması"), 0, "Bu iki akarsu bölgenin sulama ve enerji yatırımları açısından önemlidir."),
        Question(3044, "Su Varlığı", "Tortum, Düden ve Manavgat gibi örnekler hangi akarsu yer şekliyle ilişkilidir?", listOf("Şelale", "Delta", "Menderes", "Moren", "Polye"), 0, "Bu örnekler Türkiye'deki önemli şelale alanları arasında yer alır."),

        Question(3051, "Toprak ve Bitki", "Çukurova gibi delta ovalarında tarımsal verimin yüksek olmasını açıklayan en uygun seçenek hangisidir?", listOf("Alüvyal toprakların bulunması", "Kalıcı kar örtüsü", "Tundra bitkilerinin yaygınlığı", "Yüksek dağların yoğunluğu", "Çöl iklimi"), 0, "Akarsuların taşıyıp biriktirdiği alüvyonlar tarımsal açıdan verimli topraklar oluşturabilir."),
        Question(3052, "Toprak ve Bitki", "Türkiye'nin farklı iklim kuşaklarının etkisi altında bulunması aşağıdakilerden hangisini artırır?", listOf("Toprak ve bitki çeşitliliğini", "Meridyen sayısını", "Yerel saat farkını tek başına", "Gelgit genliğini", "Paraleller arası uzaklığı"), 0, "İklim çeşitliliği bitki örtüsünün ve buna bağlı toprak özelliklerinin çeşitlenmesine katkı sağlar."),
        Question(3053, "Toprak ve Bitki", "Çay tarımının Doğu Karadeniz'de gelişmesinde aşağıdakilerden hangisi daha belirleyicidir?", listOf("Nemli ve yağışlı iklim koşulları", "Yaz kuraklığının uzun sürmesi", "Çölleşme", "Kalıcı buz örtüsü", "Geniş doğal bozkırlar"), 0, "Çay yüksek nem ve yağış isteyen bir bitki olduğundan Doğu Karadeniz koşulları elverişlidir."),

        Question(3061, "Nüfus ve Yerleşme", "Nüfusun bir bölgede yoğunlaşmasında aşağıdakilerden hangisi beşerî çekim faktörüne örnektir?", listOf("Sanayi ve hizmet sektörlerinin gelişmiş olması", "Yükseltinin fazla olması", "Eğimin çok fazla olması", "Kuraklığın şiddetli olması", "Su kaynaklarının azalması"), 0, "İş ve hizmet olanakları nüfusu bölgeye çeken beşerî faktörlerdir."),
        Question(3062, "Nüfus ve Yerleşme", "Doğal nüfus artışı hesaplanırken aşağıdakilerden hangisi dikkate alınmaz?", listOf("Göç", "Doğum", "Ölüm", "Doğum ve ölüm farkı", "Nüfusun doğal değişimi"), 0, "Doğal nüfus artışı doğumlarla ölümler arasındaki farktır; göçler hesaba katılmaz."),
        Question(3063, "Nüfus ve Yerleşme", "Türkiye'de nüfusun dengesiz dağılışını açıklarken aşağıdakilerden hangisinin hem doğal hem beşerî faktörlerle birlikte değerlendirilmesi gerekir?", listOf("Yerleşme ve ekonomik faaliyetlerin dağılışı", "Meridyenlerin toplam sayısı", "Ulusal saat", "Dünya'nın günlük hareketi", "Paralel aralıklarının sabitliği"), 0, "İklim, yer şekilleri, su ve toprak gibi doğal faktörlerin yanında sanayi, tarım, turizm ve ulaşım da nüfus dağılışını etkiler."),

        Question(3071, "Tarım ve Hayvancılık", "Tiftik keçisi yetiştiriciliğiyle ilişkilendirilen il aşağıdakilerden hangisidir?", listOf("Ankara", "Rize", "Antalya", "Trabzon", "Edirne"), 0, "Tiftik keçisi Ankara çevresiyle özdeşleşmiş hayvancılık faaliyetlerinden biridir."),
        Question(3072, "Tarım ve Hayvancılık", "İpekböcekçiliğinin gelişmesi aşağıdaki faaliyetlerden hangisiyle doğrudan ilişkilidir?", listOf("Dut ağacı yetiştiriciliği", "Çay tarımı", "Zeytinliklerin genişlemesi", "Şeker pancarı üretimi", "Tütün işleme"), 0, "İpekböceğinin temel besin kaynağı dut yapraklarıdır."),
        Question(3073, "Tarım ve Hayvancılık", "Bir tarım ürününün yetişme alanını belirlemede aşağıdakilerden hangisi ilk değerlendirilmesi gereken unsurlardandır?", listOf("Sıcaklık ve su isteği", "Plaka kodu", "Liman sayısı", "Yerel saat", "Sınır kapısı sayısı"), 0, "Ürünün yetişme koşulları ile bölgenin iklim ve su şartlarının uyuşması gerekir."),

        Question(3081, "Maden ve Enerji", "Kırka aşağıdaki madenlerden hangisiyle özdeşleşmiştir?", listOf("Bor", "Taş kömürü", "Petrol", "Bakır", "Fosfat"), 0, "Kırka, bor kaynaklarıyla bilinen önemli merkezlerden biridir."),
        Question(3082, "Maden ve Enerji", "Zonguldak çevresinin enerji ham maddesi açısından öne çıkmasının temel nedeni hangisidir?", listOf("Taş kömürü", "Bor", "Petrol", "Doğalgaz", "Jeotermal"), 0, "Zonguldak çevresi taş kömürü yataklarıyla tanınır."),
        Question(3083, "Maden ve Enerji", "Bir madenin çıkarıldığı yere yakın işlenmesinin temel ekonomik gerekçesi aşağıdakilerden hangisidir?", listOf("Taşıma maliyetini azaltmak", "Enlemi değiştirmek", "Yağışı artırmak", "Yerel saati eşitlemek", "Kıyı tipini değiştirmek"), 0, "Özellikle ağır ve taşınması pahalı hammaddelerde kaynağa yakın işleme taşıma maliyetini azaltabilir."),
        Question(3084, "Maden ve Enerji", "Azerbaycan doğal gazının Anadolu üzerinden Avrupa'ya taşınmasında kullanılan proje hangisidir?", listOf("TANAP", "Kerkük-Yumurtalık", "BTC", "Mavi Akım", "Habur-Kapıkule"), 0, "TANAP, Azerbaycan doğal gazını Türkiye üzerinden Avrupa yönüne taşır."),

        Question(3091, "Sanayi ve Ulaşım", "Türkiye'nin Asya ile Avrupa arasındaki konumu ulaşım açısından hangi özelliği güçlendirir?", listOf("Transit geçişlerin önemini", "Buzul ulaşımını", "Gelgit taşımacılığını", "Çöl kervanlarının zorunluluğunu", "Mercan resifleri üzerinden taşımayı"), 0, "Kıtalar arası geçiş konumu kara, demir ve deniz ulaşımında transit önem oluşturur."),
        Question(3092, "Sanayi ve Ulaşım", "İstanbul ve Çanakkale Boğazlarının stratejik öneminde aşağıdakilerden hangisi temel rol oynar?", listOf("Denizler arasında doğal geçiş sağlamaları", "Türkiye'nin en yüksek noktaları olmaları", "Akarsuların tamamını beslemeleri", "Çöl alanlarını sulamaları", "Tarım alanlarını doğrudan artırmaları"), 0, "Boğazlar denizler arasındaki doğal geçişleri sağladıkları için stratejik ve ulaşım açısından önemlidir."),
        Question(3093, "Sanayi ve Ulaşım", "Bir sanayi tesisinin büyük bir pazarın yakınına kurulmasının temel avantajı hangisidir?", listOf("Ürünün tüketiciye ulaştırma maliyetinin ve süresinin azalması", "Yükseltinin azalması", "Yağışın artması", "Fayların durması", "Yerel saatin değişmesi"), 0, "Pazara yakınlık dağıtım ve satış süreçlerini kolaylaştırır."),

        Question(3101, "Turizm", "Kapadokya'daki peri bacalarının oluşumunda hangi süreçlerin birlikte etkili olması açıklayıcıdır?", listOf("Volkanik tüflerin aşınması ve şekillenmesi", "Mercan ve gelgit", "Buzul birikimi", "Delta birikimi", "Sadece kıyı aşındırması"), 0, "Volkanik tüfler zamanla su ve rüzgâr gibi dış kuvvetlerin etkisiyle aşınarak peri bacası şekillerini oluşturur."),
        Question(3102, "Turizm", "Uludağ, Erciyes ve Palandöken gibi merkezlerin ortak turizm özelliği hangisidir?", listOf("Kış turizmi", "Kıyı turizmi", "Çöl turizmi", "Mercan turizmi", "Delta turizmi"), 0, "Yüksek ve karlı dağlık alanlar kış turizmi için elverişli koşullar sağlar."),
        Question(3103, "Turizm", "Akdeniz ve Ege kıyılarında yaz turizminin Karadeniz kıyılarına göre daha gelişmiş olmasında hangi iklim özelliği etkilidir?", listOf("Güneşli ve sıcak günlerin daha elverişli olması", "Kışların her yerde aynı olması", "Gelgitin fazla olması", "Buzulların bulunması", "Tundranın yaygın olması"), 0, "Yaz turizmi için sıcaklık ve güneşlenme koşulları önemlidir; Akdeniz ve Ege kıyıları bu açıdan daha elverişlidir."),

        Question(3111, "Harita Bilgisi", "İzohips haritasında kapalı eğrilerin yükselti değerleri merkeze doğru artıyorsa merkezde hangi yer şekli bulunur?", listOf("Tepe", "Çukur", "Delta", "Vadi tabanı", "Kıyı ovası"), 0, "Kapalı izohipslerde yükselti merkeze doğru artıyorsa tepe gösterilir."),
        Question(3112, "Harita Bilgisi", "İki merkez arasındaki boylam farkı 5° ise yerel saat farkı kaç dakikadır?", listOf("20", "15", "25", "30", "10"), 0, "Her 1° meridyen farkı 4 dakika olduğundan 5 × 4 = 20 dakikadır."),
        Question(3113, "Harita Bilgisi", "Türkiye'nin kuzey-güney uçları arasındaki 6 paralellik farkı yaklaşık kaç kilometredir?", listOf("666 km", "111 km", "600 km", "760 km", "444 km"), 0, "Ardışık paraleller yaklaşık 111 km olduğundan 6 × 111 = 666 km kabul edilir."),
        Question(3114, "Harita Bilgisi", "Küçük ölçekli bir haritanın büyük ölçekli haritaya göre temel özelliği hangisidir?", listOf("Daha geniş alanı daha az ayrıntıyla göstermesi", "Daha dar alanı daha fazla ayrıntıyla göstermesi", "Yükseltiyi değiştirmesi", "Gerçek uzaklığı değiştirmesi", "Kuzey yönünü kaldırması"), 0, "Küçük ölçek, geniş alanı daha küçük gösterimle temsil eder ve ayrıntı azalır."),

        Question(3121, "Doğal Afetler", "Eğimli ve bitki örtüsünün zayıf olduğu bir yamaçta aşırı yağıştan sonra kütlenin aşağı doğru hareket etmesi hangi afeti düşündürür?", listOf("Heyelan", "Kuraklık", "Çığ", "Tsunami", "Volkanik püskürme"), 0, "Eğim, suya doygunluk ve zayıf tutunma koşulları heyelan riskini artırabilir."),
        Question(3122, "Doğal Afetler", "Kar örtüsünün eğimli yamaçlarda kütle halinde hareket etmesi aşağıdakilerden hangisidir?", listOf("Çığ", "Heyelan", "Erozyon", "Sel", "Kuraklık"), 0, "Çığ, eğimli yamaçlarda kar kütlesinin ani hareketidir."),

        Question(3131, "Ticaret ve Ulaşım", "İç ticaretin canlı olmasında aşağıdakilerden hangisinin birlikte etkisi vardır?", listOf("Bölgeler arasındaki üretim farklılıkları ve ulaşım olanakları", "Tüm bölgelerde aynı tarım ürününün yetişmesi", "Nüfusun tamamen eşit dağılması", "Ulaşımın gelişmemesi", "Sanayinin her yerde aynı olması"), 0, "Üretim çeşitliliği, nüfus dağılışı ve ulaşım farklılıkları bölgeler arası mal akışını artırır."),
        Question(3132, "Ticaret ve Ulaşım", "İthalat ile ihracat arasındaki farkın negatif olması hangi durumu ifade eder?", listOf("Dış ticaret açığı", "Dış ticaret fazlası", "Transit ticaret", "İç ticaret", "Serbest ticaret bölgesi"), 0, "İthalat ihracattan fazla olduğunda dış ticaret açığı oluşur."),
        Question(3133, "Ticaret ve Ulaşım", "Türkiye'nin Asya ile Avrupa arasında yer alması hangi ticaret türünde stratejik avantaj sağlar?", listOf("Transit ticaret", "Yalnızca yerel ticaret", "Yalnızca kapalı ekonomi", "Yalnızca tarımsal ticaret", "Yalnızca kıyı balıkçılığı"), 0, "Transit ticarette bir ülkenin ulaşım yollarından geçiş önemlidir; Türkiye'nin kıtalar arası konumu avantaj sağlar."),
    )
}
