create table if not exists public.account_deletion_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  reason text,
  status text not null default 'pending'
    check (status in ('pending','processing','completed','rejected')),
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.account_deletion_requests enable row level security;
revoke all on public.account_deletion_requests from anon, authenticated;