-- Admin-managed automatic notification schedule and client-readable template pool.

create table if not exists public.notification_automations (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  category text not null default 'motivation'
    check (category in ('study','streak','quiz','geography','arena','content','motivation')),
  time_local time not null,
  active boolean not null default true,
  days_mask smallint not null default 127
    check (days_mask between 0 and 127),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notification_automations enable row level security;

revoke all on public.notification_automations from anon, authenticated;
grant select on public.notification_automations to authenticated;
grant insert, update, delete on public.notification_automations to authenticated;

drop policy if exists notification_automations_active_read on public.notification_automations;
create policy notification_automations_active_read
on public.notification_automations
for select to authenticated
using (active or is_admin());

drop policy if exists notification_automations_admin_write on public.notification_automations;
create policy notification_automations_admin_write
on public.notification_automations
for all to authenticated
using (is_admin())
with check (is_admin());

drop policy if exists notification_templates_authenticated_read on public.notification_templates;
create policy notification_templates_authenticated_read
on public.notification_templates
for select to authenticated
using (active or is_admin());

grant select on public.notification_templates to authenticated;

insert into public.notification_automations (key,title,category,time_local,active)
values
('morning_study','Sabah Çalışma Hatırlatması','study','09:00',true),
('afternoon_quiz','Öğleden Sonra Mini Test','quiz','14:00',true),
('evening_review','Akşam Tekrarı','motivation','20:00',true)
on conflict (key) do nothing;

create index if not exists notification_automations_active_time_idx
  on public.notification_automations(active,time_local);
