-- Admin authorization and notification campaign hardening.
-- Idempotent because this project may already contain these objects from a
-- dashboard/manual deployment.

alter table public.profiles
  add column if not exists role text not null default 'user';

update public.profiles
set role = 'user'
where role is null;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.notification_campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  type text not null default 'announcement',
  audience text not null default 'all',
  status text not null default 'draft',
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.notification_campaigns enable row level security;

revoke all on table public.notification_campaigns from anon, authenticated;
grant select, insert, update, delete on table public.notification_campaigns to authenticated;

drop policy if exists notification_campaigns_admin_select on public.notification_campaigns;
drop policy if exists notification_campaigns_admin_insert on public.notification_campaigns;
drop policy if exists notification_campaigns_admin_update on public.notification_campaigns;
drop policy if exists notification_campaigns_admin_delete on public.notification_campaigns;

create policy notification_campaigns_admin_select
on public.notification_campaigns
for select to authenticated
using ((select public.is_admin()));

create policy notification_campaigns_admin_insert
on public.notification_campaigns
for insert to authenticated
with check (
  (select public.is_admin())
  and created_by = (select auth.uid())
);

create policy notification_campaigns_admin_update
on public.notification_campaigns
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy notification_campaigns_admin_delete
on public.notification_campaigns
for delete to authenticated
using ((select public.is_admin()));

-- Clients may create/update their own profile data, but never the role column.
revoke insert, update on table public.profiles from authenticated;

grant insert (
  id, display_name, created_at, updated_at, email, username,
  avatar_id, onboarding_completed
) on table public.profiles to authenticated;

grant update (
  display_name, updated_at, email, username, avatar_id, onboarding_completed
) on table public.profiles to authenticated;

-- No unauthenticated Data API access to profiles.
revoke select, insert, update, delete, truncate, references, trigger
on table public.profiles from anon;
